# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

Import('env')
import os

# Linux specific flags
env.Append(CPPFLAGS=['-march=armv6',
                     '-mthumb-interwork'])

# Use the OpenEmbedded cross-compilation environment
vars = Variables()
vars.Add('CROSS_COMPILE', 'Cross compile toolchain prefix', os.environ.get('CROSS_COMPILE'))
vars.Update(env)
Help(vars.GenerateHelpText(env))

# Use common CROSS_COMPILE prefix
if '' == env.subst('$CROSS_COMPILE'):
   print 'CROSS_COMPILE variable is required for Linux/ARM builds'
   if not GetOption('help'):
      Exit(1)

env['CC']   = env['CROSS_COMPILE'] + 'gcc'
env['CXX']  = env['CROSS_COMPILE'] + 'g++'
env['LINK'] = env['CROSS_COMPILE'] + 'gcc'



