# Copyright (c) AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
 
Import('secenv')
Import ('classes') 
 
jnienv = secenv.Clone();
 
# Generate JNI headers
#jni_headers = jnienv.JavaH(Dir('.').srcnode().abspath, classes)

jnienv.Append(CPPPATH = '.')
jnienv.Prepend(LIBS = ['ajsecmgr','ajsecstorage'])

if jnienv['BR'] == 'on':
    jnienv.Append(LIBPATH = ['$DISTDIR' + '/cpp/lib'])
    jnienv.Prepend(LIBS = [jnienv['ajrlib']])

# JNI library
objs = jnienv.SharedObject(Glob('*.cc'))
#jnienv.Requires(objs, jni_headers)

libajsecmgr_java = jnienv.SharedLibrary('ajsecmgr_java', objs)
 
Return('libajsecmgr_java')
