# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('env')

srcs = env.Glob('*.cc') + env.Glob('../common/*.cc')
objs = env.Object(srcs)

env.Install('$CONFIG_DISTDIR/bin/samples', 'ConfigService.conf')
env.Install('$CONFIG_DISTDIR/bin/samples', 'FactoryConfigService.conf')

prog = env.Program('ConfigService', objs)

Return('prog')