/******************************************************************************
 *  * 
 *    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
 *    Source Project Contributors and others.
 *    
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0

 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alljoyn_bus_samples_simpleclient_Client */

#ifndef _Included_org_alljoyn_bus_samples_simpleclient_Client
#define _Included_org_alljoyn_bus_samples_simpleclient_Client
#ifdef __cplusplus
extern "C" {
#endif
#undef org_alljoyn_bus_samples_simpleclient_Client_BUSNAMEITEM_ADD
#define org_alljoyn_bus_samples_simpleclient_Client_BUSNAMEITEM_ADD 1L
#undef org_alljoyn_bus_samples_simpleclient_Client_BUSNAMEITEM_REMOVE
#define org_alljoyn_bus_samples_simpleclient_Client_BUSNAMEITEM_REMOVE 2L
#undef org_alljoyn_bus_samples_simpleclient_Client_BUSNAMEITEM_DISCONNECT
#define org_alljoyn_bus_samples_simpleclient_Client_BUSNAMEITEM_DISCONNECT 3L
/*
 * Class:     org_alljoyn_bus_samples_simpleclient_Client
 * Method:    simpleOnCreate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_alljoyn_bus_samples_simpleclient_Client_simpleOnCreate
    (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_bus_samples_simpleclient_Client
 * Method:    simpleOnDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_samples_simpleclient_Client_simpleOnDestroy
    (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_samples_simpleclient_Client
 * Method:    simplePing
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_alljoyn_bus_samples_simpleclient_Client_simplePing
    (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     org_alljoyn_bus_samples_simpleclient_Client
 * Method:    joinSession
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_alljoyn_bus_samples_simpleclient_Client_joinSession
    (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_bus_samples_simpleclient_Client
 * Method:    leaveSession
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_alljoyn_bus_samples_simpleclient_Client_leaveSession
    (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif