# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('env')

lib_env = env.Clone()
lib_env.Append(CPPPATH = [env['INCDIR_COMMON']])

sqlite_dir = lib_env['SQLITE_DIR']

srcs = Glob('*.cc')
objs = lib_env.Object(srcs)

libs = []

# Header files
lib_env.Append(CPPPATH = ['.'])
lib_env.Append(CPPPATH = sqlite_dir)
lib_env.Append(CPPPATH = ['../inc'])
lib_env.Append(CPPPATH = ['../../agent/inc'])
lib_env.Append(CPPPATH = ['../../external/sqlite3'])

# Static library
libs.append(lib_env.StaticLibrary('ajsecstorage', objs))

# Shared library
if lib_env.get('LIBTYPE', 'static') != 'static':
    shobjs = lib_env.SharedObject(srcs)
    libs.append(lib_env.SharedLibrary('ajsecstorage', shobjs))

# Files for SDK
if lib_env['OS_GROUP'] in ['windows']:
    lib_env.Install('$CPP_DISTDIR/samples/securitymgr/storage/src', lib_env.Glob('*.cc'))
    lib_env.Install('$CPP_DISTDIR/samples/securitymgr/storage/src', lib_env.Glob('*.h'))
    lib_env.Install('$CPP_DISTDIR/samples/securitymgr/storage/inc/alljoyn/securitymgr/storage', lib_env.Glob('../inc/alljoyn/securitymgr/storage/*.h'))

Return ('libs')