# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('about_env')

classes = about_env.Java('$OBJDIR_ABOUT/java/classes', source = ['org'])
if about_env['dep_jars']:
    about_env.Depends(classes, about_env['dep_jars'])
jars = about_env.Jar(target = 'alljoyn_about', source = classes)

Return('jars')