# Copyright (c) 2013, 2014 AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('env')
clientDistDir = '$DISTDIR/cpp/samples/SampleDaemon'

# Program binary
prog = [ env.Program('SampleDaemon', 'SampleDaemon.cc') ]

# The sample daemon binary is intended to be used by thin client apps and is
# packaged with ThinClient SDK (Win7/Linux). It sets credentials so that
# the thin client apps connect to it in a trusted manner (meaning: requires BR)

if env['BR'] == 'on' and env['OS'] in ['linux', 'win7']:
    env.Install('$DISTDIR/cpp/bin/samples', prog )
    env.Install(clientDistDir, env.Glob('*.cc'))
