# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('env')
clientDistDir = '$C_DISTDIR/samples/secure/door'

app_env = env.Clone()
app_env.Prepend(LIBS = ['alljoyn'])

# Sample Programs
progs = [
    env.Program('SecureDoorProvider_C', ['secure_door_provider.cc', 'secure_door_common.cc']),
    env.Program('SecureDoorConsumer_C', ['secure_door_consumer.cc', 'secure_door_common.cc'])
    ]

if env['OS'] != 'android':
     env.Install('$C_DISTDIR/bin/samples', progs )
     env.Install(clientDistDir, env.Glob('*.cc') + env.Glob('*.h'))