# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#

Import('env')

test_env = env.Clone()

if test_env['BR'] == 'on':
    #Build apps with bundled daemon support
    test_env.Prepend(LIBS = [test_env['ajrlib']])

test_env.Prepend(LIBS = [test_env['ALLJOYN_C_LIB_STATIC']])

test_programs = ['bbcclient', 'bbcservice']
built_test_programs = []
for test_p in test_programs:
    test_obj = test_env.Object(test_p)
    built_test_programs.append(test_env.Program(test_p,  [test_obj]))

if test_env['OS_GROUP'] != 'windows':
    test_env.Install('$C_DISTDIR/bin', built_test_programs)