# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('env')

app_env = env.Clone()

app_env.Append(CPPPATH = [env['INCDIR_COMMON']])
app_env.Append(CPPPATH = ['../agent/inc/'])
app_env.Append(CPPPATH = ['../storage/inc/'])

app_env.Append(LIBPATH = '../external/sqlite3')
app_env.Append(LIBPATH = '../agent/src')
app_env.Append(LIBPATH = '../storage/src')

app_env.Prepend(LIBS = ['sqlite3'])
app_env.Prepend(LIBS = ['ajsecmgr'])
app_env.Prepend(LIBS = ['ajsecstorage'])

secmgrapp = app_env.Program(target='secmgr', source=['secmanager.cc'])

# Files for SDK
if app_env['OS_GROUP'] in ['windows']:
    app_env.Install('$CPP_DISTDIR/bin/samples', secmgrapp )
    app_env.Install('$CPP_DISTDIR/samples/securitymgr/cli', env.Glob('secmanager.cc'))

Return('secmgrapp')