# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#
import os.path
Import('env')

sdk_methodsClient_sample = env.Java('$OBJDIR_ALLJOYN_JAVA/samples/JavaSDKDoc/JavaSDKDocMethodsClient', 'src',
                                    JAVACLASSPATH=env.GetBuildPath(env.subst('$JARDIR/alljoyn.jar')))

#if the manifest file does not yet exist create it unless clean has be specified.
if not env.GetOption('clean'):
    if not os.path.isfile('MANIFEST.MF'):
        manifest = ("Manifest-Version: 1.0\n" +
                    "Class-Path: alljoyn.jar\n" +
                    "Main-Class: org.alljoyn.bus.samples.Client\n")
        file = open('MANIFEST.MF', 'w')
        file.write(manifest)
        file.close()

sdk_methodsClient_sample.append('MANIFEST.MF')

env.Jar('$JARDIR/JavaSDKDocMethodsClient.jar', sdk_methodsClient_sample)
env.Requires(sdk_methodsClient_sample, '$JARDIR/alljoyn.jar')

#add the sample to the dist with out adding the build files.
# The return value is the collection of files installed in the build destination.
returnValue = env.Install('$JAVA_DISTDIR/samples/JavaSDKDoc/JavaSDKDocMethodsClient', ['src', '.classpath', '.project'])

#clean up the created manifest file
env.Clean('.', sdk_methodsClient_sample)
#clean the build folder that remains after cleaning all other files.
env.Clean('.', 'build')

Return('returnValue')