# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 
import os
Import('env')

cwd = os.getcwd()

msiDestination = '../../build/Win7'
msiSource='./release/AllJoynWinInstaller.msi'

# Always rebuild the MSI so that multiple builds of debug, release, CPU can be made and
# a new MSI is made after each one. 
if os.path.exists(msiSource):
    os.remove(msiSource)

programFiles=''

if os.environ.has_key('ProgramFiles(x86)'):
    programFiles=os.environ['ProgramFiles(x86)']
elif os.environ.has_key('ProgramFiles'):
    programFiles=os.environ['ProgramFiles']
else:
    print 'Program files directory not found.'
    Exit(1)

if env.has_key('MSVC_VERSION'):
    msvcVer = env['MSVC_VERSION']
else:
    print 'Visual Studio version not found.'
    Exit(1)

devEnv = '"' + programFiles + '\Microsoft Visual Studio ' + msvcVer + '\Common7\IDE\devenv.exe"' 
cmd = cwd + '\MakeAjSdkMsi.cmd ' + cwd + ' ' + devEnv

Msi = env.Command(msiSource, Dir('$DISTDIR'), cmd)
installedMsi = env.Install(msiDestination, Msi)

Return ('installedMsi')