# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#
import os

Import('env')

clientDistDir = '$CPP_DISTDIR/samples/eventaction'

enaEnv = env.Clone()

# Install sample source
if enaEnv['OS'] == 'android':
    enaEnv.Install(clientDistDir + '/Android', 'Android/AndroidManifest.xml')
    enaEnv.Install(clientDistDir + '/Android', 'Android/.classpath')
    enaEnv.Install(clientDistDir + '/Android', 'Android/.project')
    enaEnv.Install(clientDistDir + '/Android', 'Android/project.properties')
    enaEnv.Install(clientDistDir + '/Android', enaEnv.Dir('Android/jni').srcnode())
    enaEnv.Install(clientDistDir + '/Android', enaEnv.Dir('Android/src').srcnode())
    enaEnv.Install(clientDistDir + '/Android', enaEnv.Dir('Android/res').srcnode())

# This sample depends on the About Service
if enaEnv['OS'] in ['linux', 'darwin', 'openwrt']:
    enaEnv.Append(CPPPATH = [ enaEnv.Dir('$CPP_DISTDIR/../about/inc') ])
    enaEnv.Append(LIBPATH = [ enaEnv.Dir('$CPP_DISTDIR/../about/lib') ])

    enaEnv.Prepend(LIBS = ['alljoyn_about'])
    ruleSrcFiles = enaEnv.Glob('SimpleRulesEngine/*.cc')
    ruleSrcFiles += enaEnv.Glob('SimpleRulesEngine/posix/*.cc')
    enaEnv.Program('sample_rule_app', ruleSrcFiles)
    enaEnv.Install('$CPP_DISTDIR/bin/samples', ['sample_rule_app'] )