# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

Import('env')

# Install sample source
if env['OS'] == 'android':
    clientDistDir = '$CPP_DISTDIR/samples/simple/client'
    env.Install(clientDistDir, 'android/client/AndroidManifest.xml')
    env.Install(clientDistDir, 'android/client/.classpath')
    env.Install(clientDistDir, 'android/client/.project')
    env.Install(clientDistDir, 'android/client/default.properties')
    env.Install(clientDistDir, Dir('android/client/.settings').srcnode())
    env.Install(clientDistDir, Dir('android/client/jni').srcnode())
    env.Install(clientDistDir, Dir('android/client/src').srcnode())
    env.Install(clientDistDir, Dir('android/client/res').srcnode())

    serviceDistDir = '$CPP_DISTDIR/samples/simple/service'
    env.Install(serviceDistDir, 'android/service/AndroidManifest.xml')
    env.Install(serviceDistDir, 'android/service/.classpath')
    env.Install(serviceDistDir, 'android/service/.project')
    env.Install(serviceDistDir, 'android/service/default.properties')
    env.Install(serviceDistDir, Dir('android/service/.settings').srcnode())
    env.Install(serviceDistDir, Dir('android/service/jni').srcnode())
    env.Install(serviceDistDir, Dir('android/service/src').srcnode())
    env.Install(serviceDistDir, Dir('android/service/res').srcnode())