# Copyright (c) 2014, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('secenv')

lib_env = secenv.Clone()

srcs = Glob('*.cc')

lib_env.Prepend(LIBS = ['dl', 'sqlite3'])

libs = []

# Header files
lib_env.Append(CPPPATH = ['.'])
lib_env.Append(CPPPATH = ['../../../../../../../storage/inc'])
lib_env.Append(CPPPATH = ['../../../../../../../core/inc/'])

# Static library
objs = lib_env.Object(srcs)
libs.append(lib_env.StaticLibrary('ajsecstorage', objs))

# Shared library
if lib_env.get('LIBTYPE', 'static') != 'static':
    shobjs = lib_env.SharedObject(srcs)
    libs.append(lib_env.SharedLibrary('ajsecstorage', shobjs))

Return ('libs')
