# Copyright (c) 2011, 2013, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 

import os
Import('env')

docenv = env.Clone()
docenv['ENV']['UNITY_DISTDIR'] = str(env.Dir('$UNITY_DISTDIR'))

# The return value is the collection of files installed in the build destination.
installDocs = []

# Build docs
if env['DOCS'] == 'html':
    generateDocs = docenv.Doxygen(source=['Doxygen_html'])
    installDocs = docenv.Install('$UNITY_DISTDIR/docs', Dir('html'))
    docenv.Depends(generateDocs, '../src/Status.cs')
    docenv.Depends(installDocs, generateDocs)

# Build Alias to make cleaning, building and rebuilding the documentation when
# working only on the documentation simpler. This can be run by using
# `scons unity_docs`
docenv.Alias('unity_docs', installDocs)

Return('installDocs')
