# Copyright (c) 2010 - 2013, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 

Import('env')

# Install sample source
clientDistDir = '$CPP_DISTDIR/samples/chat'
if env['OS'] == 'android':
    env.Install(clientDistDir, 'android/AndroidManifest.xml')
    env.Install(clientDistDir, 'android/.classpath')
    env.Install(clientDistDir, 'android/.project')
    env.Install(clientDistDir, 'android/default.properties')
    env.Install(clientDistDir, env.Dir('android/jni').srcnode())
    env.Install(clientDistDir, env.Dir('android/src').srcnode())
    env.Install(clientDistDir, env.Dir('android/res').srcnode())

elif env['OS'] in ['linux', 'darwin']:
    env.Program('chat', ['linux/chat.cc'])
    env.Install('$CPP_DISTDIR/bin/samples', ['chat'])
    env.Install(clientDistDir, env.Glob('linux/*.cc'))
    env.Install(clientDistDir, env.Glob('linux/Make*'))

elif env['OS_GROUP'] == 'windows':
    env.Program('chat', ['linux/chat.cc'])
    env.Install('$CPP_DISTDIR/bin/samples', ['chat.exe'])
    env.Install(clientDistDir, env.Glob('linux/*.cc'))
    #install Visual Studio solution files
    env.Install(clientDistDir+'/VC2008Win7', 'linux/VC2008Win7/VC2008Win7.sln')
    env.Install(clientDistDir+'/VC2008Win7/chatsample', 'linux/VC2008Win7/chatsample/chatsample.vcproj')
