# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

Import('env')

# Install sample source
clientDistDir = '$CPP_DISTDIR/samples/chat'
if env['OS'] == 'android':
    env.Install(clientDistDir, 'android/AndroidManifest.xml')
    env.Install(clientDistDir, 'android/.classpath')
    env.Install(clientDistDir, 'android/.project')
    env.Install(clientDistDir, 'android/default.properties')
    env.Install(clientDistDir, env.Dir('android/jni').srcnode())
    env.Install(clientDistDir, env.Dir('android/src').srcnode())
    env.Install(clientDistDir, env.Dir('android/res').srcnode())

elif env['OS'] in ['linux', 'darwin']:
    env.Program('chat', ['linux/chat.cc'])
    env.Install('$CPP_DISTDIR/bin/samples', ['chat'])
    env.Install(clientDistDir, env.Glob('linux/*.cc'))
    env.Install(clientDistDir, env.Glob('linux/Make*'))

elif env['OS_GROUP'] == 'windows':
    env.Program('chat', ['linux/chat.cc'])
    env.Install('$CPP_DISTDIR/bin/samples', ['chat.exe'])
    env.Install(clientDistDir, env.Glob('linux/*.cc'))
    #install Visual Studio solution files
    env.Install(clientDistDir+'/VC2008Win7', 'linux/VC2008Win7/VC2008Win7.sln')
    env.Install(clientDistDir+'/VC2008Win7/chatsample', 'linux/VC2008Win7/chatsample/chatsample.vcproj')