# Copyright AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('env')

lib_env = env.Clone()

lib_env.Append(CPPPATH = ['../inc'])

srcs = Glob('*.cc')

# Static library
static_objs = lib_env.Object(srcs)
libs = lib_env.StaticLibrary('ajsecmgr', static_objs)

# Shared library
if lib_env.get('LIBTYPE', 'static') != 'static':
    shared_objs = lib_env.SharedObject(srcs)
    libs.append(lib_env.SharedLibrary('ajsecmgr', shared_objs))

# Files for SDK
if lib_env['OS_GROUP'] in ['windows']:
    lib_env.Install('$CPP_DISTDIR/samples/securitymgr/agent/src', lib_env.Glob('*.cc'))
    lib_env.Install('$CPP_DISTDIR/samples/securitymgr/agent/src', lib_env.Glob('*.h'))
    lib_env.Install('$CPP_DISTDIR/samples/securitymgr/agent/inc/alljoyn/securitymgr', lib_env.Glob('../inc/alljoyn/securitymgr/*.h'))

Return ('libs')
