# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('env')

lib_env = env.Clone()

lib_env.Append(CPPPATH = ['../inc'])
lib_env.Append(CPPPATH = [env['INCDIR_COMMON']])

srcs = Glob('*.cc')

# Static library
static_objs = lib_env.Object(srcs)
libs = lib_env.StaticLibrary('ajsecmgr', static_objs)

# Shared library
if lib_env.get('LIBTYPE', 'static') != 'static':
    shared_objs = lib_env.SharedObject(srcs)
    libs.append(lib_env.SharedLibrary('ajsecmgr', shared_objs))

# Files for SDK
if lib_env['OS_GROUP'] in ['windows']:
    lib_env.Install('$CPP_DISTDIR/samples/securitymgr/agent/src', lib_env.Glob('*.cc'))
    lib_env.Install('$CPP_DISTDIR/samples/securitymgr/agent/src', lib_env.Glob('*.h'))
    lib_env.Install('$CPP_DISTDIR/samples/securitymgr/agent/inc/alljoyn/securitymgr', lib_env.Glob('../inc/alljoyn/securitymgr/*.h'))

Return ('libs')