# Copyright (c) 2013, 2014, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('about_env')

if about_env['OS_CONF'] in ['linux', 'openwrt', 'windows']:
    local_env = about_env.Clone()

    local_env.Prepend(LIBS = ['alljoyn_about'])

    if local_env['BR'] == 'on' and local_env.has_key('brobj') and local_env.has_key('ajrlib'):
        # Build apps with bundled daemon support
        local_env.Prepend(LIBS = [local_env['brobj'], local_env['ajrlib']])

    # Sample programs
    sample_dirs = [
        'AboutClientSample',
        'AboutServiceSample'
        ]

    exports = { 'env': local_env}
    progs = [ local_env.SConscript('%s/SConscript' % sampleapp, exports = exports) for sampleapp in sample_dirs ]

else:
    progs = []

Return('progs')
