# Copyright AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('env')
clientDistDir = '$DISTDIR/cpp/samples/TrustedTLSampleRN'

# Program binary
prog = [ env.Program('TrustedTLSampleRN', 'TrustedTLSampleRN.cc') ]

# The Trusted Thin Library Sample Routing Node binary is intended to be used
# by thin library apps and is packaged with the Thin Library SDK (Win7/Linux).
# It sets credentials so that thin library apps may connect to it in a trusted
# manner.  The fact that the program sets credentials implies a bundled router
# configuration.

if env['BR'] == 'on' and env['OS'] in ['linux', 'win7']:
    env.Install('$DISTDIR/cpp/bin/samples', prog )
    env.Install(clientDistDir, env.Glob('*.cc'))
