# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#

Import('env')
clientDistDir = '$DISTDIR/cpp/samples/TrustedTLSampleRN'

# Program binary
prog = [ env.Program('TrustedTLSampleRN', 'TrustedTLSampleRN.cc') ]

# The Trusted Thin Library Sample Routing Node binary is intended to be used
# by thin library apps and is packaged with the Thin Library SDK (Win7/Linux).
# It sets credentials so that thin library apps may connect to it in a trusted
# manner.  The fact that the program sets credentials implies a bundled router
# configuration.

if env['BR'] == 'on' and env['OS'] in ['linux', 'win7', 'win10' ]:
    env.Install('$DISTDIR/cpp/bin/samples', prog )
    env.Install(clientDistDir, env.Glob('*.cc'))