# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 
Import('env')
clientDistDir = '$CPP_DISTDIR/samples/aboutlistener'

# Sample Programs
progs = [
    env.Program('AboutListener',  ['AboutListener.cc']),
    ]

if env['OS_GROUP'] in ['windows', 'posix']:
    env.Install('$CPP_DISTDIR/bin/samples', progs )
    env.Install(clientDistDir, env.Glob('*.cc'))