# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('config_env')

sample_env = config_env.Clone()

sample_env.Append(JAVACLASSPATH = str(config_env.File('$DISTDIR/config/jar/alljoyn_config.jar')))
sample_env['dep_jars'].append('$DISTDIR/config/jar/alljoyn_config.jar')

if sample_env['OS'] == 'linux' or sample_env['OS_GROUP'] == 'windows':
    jars = sample_env.SConscript('java/SConscript', exports = ['sample_env'])
else:
    jars = []

Return('jars')