/******************************************************************************
 *  * 
 *    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
 *    Source Project Contributors and others.
 *    
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0

 *
 ******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alljoyn_bus_samples_chat_Chat */

#ifndef _Included_org_alljoyn_bus_samples_chat_Chat
#define _Included_org_alljoyn_bus_samples_chat_Chat
#ifdef __cplusplus
extern "C" {
#endif
#undef org_alljoyn_bus_samples_chat_Chat_DIALOG_CONNECT
#define org_alljoyn_bus_samples_chat_Chat_DIALOG_CONNECT 1L
#undef org_alljoyn_bus_samples_chat_Chat_DIALOG_ADVERTISE
#define org_alljoyn_bus_samples_chat_Chat_DIALOG_ADVERTISE 2L
#undef org_alljoyn_bus_samples_chat_Chat_DIALOG_JOIN_SESSION
#define org_alljoyn_bus_samples_chat_Chat_DIALOG_JOIN_SESSION 3L
/*
 * Class:     org_alljoyn_bus_samples_chat_Chat
 * Method:    jniOnCreate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_alljoyn_bus_samples_chat_Chat_jniOnCreate
    (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_bus_samples_chat_Chat
 * Method:    jniOnDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_samples_chat_Chat_jniOnDestroy
    (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_samples_chat_Chat
 * Method:    sendChatMsg
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_alljoyn_bus_samples_chat_Chat_sendChatMsg
    (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_bus_samples_chat_Chat
 * Method:    advertise
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_alljoyn_bus_samples_chat_Chat_advertise
    (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_bus_samples_chat_Chat
 * Method:    joinSession
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_alljoyn_bus_samples_chat_Chat_joinSession
    (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif