# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#

Import('env')

snippets_env = env.Clone()

if snippets_env['BR'] == 'on':
    # Build apps with bundled daemon support
    snippets_env.Prepend(LIBS = [snippets_env['ajrlib']])

# only include command line samples, unit test, test programs if we are not
# building for iOS. No support on iOS for command line applications.
if not ((snippets_env['OS'] == 'darwin' and snippets_env['CPU'] in ['arm', 'armv7', 'armv7s', 'arm64']) or snippets_env['OS'] == 'iOS'):
    snippets_env.Program('usingmsgarg',  ['usingmsgarg.cpp'])
    snippets_env.Program('create_interface_from_xml_interface', ['create_interface_from_xml_interface.cpp'])
    snippets_env.Program('create_interface_from_xml_node', ['create_interface_from_xml_node.cpp'])
    snippets_env.Program('create_interface_using_code', ['create_interface_using_code.cpp'])