# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

import os
import string
Import('env')

# AllJoyn Java binding
# enable UTF-8 character in unit tests
env.Append(JAVACFLAGS = ['-encoding', 'UTF-8'])
test_classes = env.Java('$OBJDIR_ALLJOYN_JAVA/test/classes', '.', JAVACLASSPATH=os.pathsep.join(
        [env['JAVACLASSPATH'], env.GetBuildPath(env.subst('$JARDIR/alljoyn.jar'))]))

# The return value is the collection of files installed in the build destination.
returnValue = env.Jar('$JARDIR/alljoyn_test.jar', test_classes)
env.Requires(test_classes, '$JARDIR/alljoyn.jar')

Return('returnValue')