# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('sample_env')

classes = sample_env.Java(sample_env.Dir('$OBJDIR_ABOUT/java/samples/classes').srcnode(), 'src')
sample_env.Depends(classes, sample_env['dep_jars'])
# scons does not have support for Java 7 yet.  When building with Java 7 an
# additional class is generated that scons is unaware of. So we apply a work around
# to clean the class and to make sure the class is included in the resulting jar
# file
sample_env.Clean(classes, sample_env.Dir('$OBJDIR_ABOUT/java/samples/classes').srcnode())

jar = sample_env.Jar(target = 'about_client_sample_legacy', source = [sample_env.Dir('$OBJDIR_ABOUT/java/samples/classes').srcnode(), 'MANIFEST.MF'], JARCHDIR='$SOURCE')

Return('jar')