# Copyright AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('config_env')

if config_env.has_key('_ALLJOYN_JAVA_'):
    config_env.Append(JAVACLASSPATH = [ str(config_env.File('$DISTDIR/java/jar/alljoyn.jar')),
                                        str(config_env.File('$DISTDIR/java/jar/alljoyn_about.jar')) ])
    config_env['dep_jars'] = [ '$DISTDIR/java/jar/alljoyn.jar',
                               '$DISTDIR/java/jar/alljoyn_about.jar' ]
else:
    config_env.Append(JAVACLASSPATH = [ str(config_env.File('$ALLJOYN_DISTDIR/java/jar/alljoyn.jar')),
                                        str(config_env.File('$ALLJOYN_DISTDIR/java/jar/alljoyn_about.jar')) ])
    config_env['dep_jars'] = [ ]

# Currently the java ConfigService directly and indirectly uses a lot of
# deprecated code, so we turn off deprecation warnings here. A single
# warning it still printed letting us know we are using deprecated code.
# This is better than 100s of warnings across the ConfigService code.
config_env.Append(JAVACFLAGS = ['-Xlint:-deprecation'])

jars = []
jars += config_env.SConscript('src/SConscript', exports = ['config_env']),

# Sample programs
jars += config_env.SConscript('samples/SConscript', exports = ['config_env'])

config_env.Install('$DISTDIR/java/jar', jars)
