# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('config_env')

if config_env.has_key('_ALLJOYN_JAVA_'):
    config_env.Append(JAVACLASSPATH = [ str(config_env.File('$DISTDIR/java/jar/alljoyn.jar')),
                                        str(config_env.File('$DISTDIR/java/jar/alljoyn_about.jar')) ])
    config_env['dep_jars'] = [ '$DISTDIR/java/jar/alljoyn.jar',
                               '$DISTDIR/java/jar/alljoyn_about.jar' ]
else:
    config_env.Append(JAVACLASSPATH = [ str(config_env.File('$ALLJOYN_DISTDIR/java/jar/alljoyn.jar')),
                                        str(config_env.File('$ALLJOYN_DISTDIR/java/jar/alljoyn_about.jar')) ])
    config_env['dep_jars'] = [ ]

# Currently the java ConfigService directly and indirectly uses a lot of
# deprecated code, so we turn off deprecation warnings here. A single
# warning it still printed letting us know we are using deprecated code.
# This is better than 100s of warnings across the ConfigService code.
config_env.Append(JAVACFLAGS = ['-Xlint:-deprecation'])

jars = []
jars += config_env.SConscript('src/SConscript', exports = ['config_env']),

# Sample programs
jars += config_env.SConscript('samples/SConscript', exports = ['config_env'])

config_env.Install('$DISTDIR/java/jar', jars)