# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

import os
import sys
sys.path.append('../../build_core/tools/scons')
Import('env')

if env['OS'] == 'android':
	main_classes = env.Java('$CLASSDIR', source = ['.'], JAVACLASSPATH=os.environ.get('CLASSPATH'))
	alljoyn_jar = env.Jar('$JS_DISTDIR/libs/alljoyn.jar', source = [main_classes])

Return('alljoyn_jar')