# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

Import('env')

clientDistDir = '$C_DISTDIR/samples/basic'

# Sample Programs
progs = [
    env.Program('basic_c_service',  ['basic_c_service.c']),
    env.Program('basic_c_client',   ['basic_c_client.c']),
]

if env['OS'] in ['linux', 'darwin']:
    env.Install('$C_DISTDIR/bin/samples', progs )
    env.Install(clientDistDir, env.Glob('*.c'))