# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('env')

agent_env = env.Clone()

# Temporary fix until ASACORE-2942 is resolved
agent_env.Append(CPPPATH = [env['INCDIR_COMMON']])


agent_env.SConscript('src/SConscript', exports = {'env': env})
agent_env.SConscript('unit_test/SConscript', exports = {'env': env})