# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('env')

app_env = env.Clone()
app_env.Append(CPPPATH = ['#agent/inc'])
app_env.Append(CPPPATH = ['#agent/src'])
app_env.Append(CPPPATH = ['#storage/inc'])
app_env.Append(LIBPATH =  '$SEC_DISTDIR/lib')
app_env.Prepend(LIBS = ['ajsecmgr', 'ajsecstorage'])

if app_env['BR'] == 'on':
        # Build apps with bundled daemon support
        app_env.Prepend(LIBS = [app_env['ajrlib']])

# build app
test_app = app_env.Program(target='multipeer_claim',
                           source=[Glob('*.cc')])

# install run scripts
script_dict = {
                '%PREFIX%': Dir('.').abspath,
                '%LIBPATH%': app_env.CreateLibPath(),
                '%TESTAPP%': test_app[0].name
              }
script = app_env.Substfile('run.sh.in', SUBST_DICT=script_dict)
app_env.AddPostAction(script, Chmod(script[0].abspath, 0755))