# Copyright (c) 2010 - 2011, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 

Import('env')
 
import os
 

 # Indicate that this SConscript file has been loaded already
env['_ALLJOYNSTREAMING_'] = True

# Clone env so don't pollute the shared environment
locenv = env.Clone()

vars = Variables()
vars.Add(PathVariable('ALLJOYN_DIST', 'AllJoyn build dist directory', os.environ.get('ALLJOYN_DIST')))
vars.Add(PathVariable('COMMON_DIR', 'AllJoyn Common directory', os.environ.get('COMMON_DIR')))
vars.Update(locenv)

Help(vars.GenerateHelpText(locenv))
if '' == locenv.subst('$ALLJOYN_DIST'):
    print 'Missing required build variable ALLJOYN_DIST'
    Exit()

if '' == locenv.subst('$COMMON_DIR'):
    print 'Missing required build variable COMMON_DIR'
    Exit()

locenv.Append(CPPPATH=['$COMMON_DIR\\inc'])
locenv.Append(CPPPATH=[locenv.Dir('inc').srcnode()])
locenv.VariantDir('$OBJDIR', 'src', duplicate=0)
Export('locenv')
common_objs = locenv.SConscript('common/SConscript', variant_dir='$OBJDIR/common', duplicate=0)
locenv.SConscript('src/SConscript', variant_dir='$OBJDIR', exports=['common_objs'])
