/*------------------------------------------------------------------------------
* This is an autogenerated or copied file which AllSeen Alliance,
* as author hereby dedicates to the public domain.  Additionally, THIS
* SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND ANY CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE,
* AND OF GOOD TITLE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
* CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
* OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
* ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*------------------------------------------------------------------------------*/
////////////////////////////////////////////////////////////////////////////////
//
//  ALLJOYN MODELING TOOL - GENERATED CODE
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//
//  DoorObject.m
//
////////////////////////////////////////////////////////////////////////////////

#import "DoorObject.h"

////////////////////////////////////////////////////////////////////////////////
//
//  Objective-C Bus Object implementation for DoorObject
//
////////////////////////////////////////////////////////////////////////////////

@implementation DoorObject

- (instancetype)initWithLocation:(NSString *)location
                         keyCode:(NSNumber *)keyCode
                          isOpen:(BOOL)isOpen
                   busAttachment:(AJNBusAttachment *)busAttachment
                            path:(NSString *)path
{
    self = [super initWithBusAttachment:busAttachment onPath:path];
    if (self) {
        [super setLocation:location];
        [super setKeyCode:keyCode];
        [super setIsOpen:isOpen];
    }
    return self;
}

- (void)setIsOpen:(BOOL)IsOpen
{
    NSLog(@"%s", __PRETTY_FUNCTION__);
    [super setIsOpen:IsOpen];
    AJNMessageArgument *msgProperty = [[AJNMessageArgument alloc] init];
    [msgProperty setValue:@"b", IsOpen];
    [msgProperty stabilize];
    [self emitPropertyWithName:@"IsOpen" onInterfaceWithName:@"com.example.Door" changedToValue:msgProperty inSession:0];
}

- (void)setKeyCode:(NSNumber *)KeyCode
{
    [super setKeyCode:KeyCode];
    AJNMessageArgument *msgProperty = [[AJNMessageArgument alloc] init];
    [msgProperty setValue:@"u", [KeyCode unsignedIntValue]];
    [msgProperty stabilize];
    [self emitPropertyWithName:@"KeyCode" onInterfaceWithName:@"com.example.Door" changedToValue:msgProperty inSession:0];
}

- (void)setLocation:(NSString *)Location
{
    [super setLocation:Location];
    AJNMessageArgument *msgProperty = [[AJNMessageArgument alloc] init];
    [msgProperty setValue:@"s", [Location UTF8String]];
    [msgProperty stabilize];
    [self emitPropertyWithName:@"Location" onInterfaceWithName:@"com.example.Door" changedToValue:msgProperty inSession:0];
}

- (void)open:(AJNMessage *)methodCallMessage
{
    if(!self.IsOpen) {
        NSLog(@"%s", __PRETTY_FUNCTION__);
        self.IsOpen = YES;
    }
}

- (void)close:(AJNMessage *)methodCallMessage
{
    if(self.IsOpen) {
        self.IsOpen = NO;
    }
}

- (void)knockAndRun:(AJNMessage *)methodCallMessage
{
    // TODO: complete the implementation of this method
    //
    // @throw([NSException exceptionWithName:@"NotImplementedException" reason:@"You must implement this method" userInfo:nil]);
}


@end

////////////////////////////////////////////////////////////////////////////////
