# Copyright (c) 2010 - 2013, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 

Import('env')

if env['OS'] != 'win8':
    # Basic Sample programs
    env.SConscript('basic/SConscript')

    # Simple Sample programs
    env.SConscript('simple/SConscript')

    # Security Sample programs
    env.SConscript('secure/SConscript')

    # Chat Sample program
    env.SConscript('chat/SConscript')

    # File transfer Sample program
    env.SConscript('FileTransfer/SConscript')

    # Sample Daemon program
    env.SConscript('SampleDaemon/SConscript')

# Install readme
if env['OS_CONF'] == 'windows':
    env.InstallAs('$CPP_DISTDIR/samples/README.txt', 'README.windows.txt')
elif env['OS_CONF'] == 'android':
    env.InstallAs('$CPP_DISTDIR/samples/README.txt', 'README.android.txt')
elif env['OS_CONF'] == 'linux':
    env.InstallAs('$CPP_DISTDIR/samples/README.txt', 'README.linux.txt')
