# Copyright (c) 2010 - 2014, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 

Import('env')

samples_env = env.Clone()

if samples_env['BR'] == 'on':
    # Build apps with bundled daemon support
    samples_env.Prepend(LIBS = [samples_env['brobj'], samples_env['ajrlib']])

# About feature sample programs
samples_env.SConscript('about/SConscript', exports = {'env': samples_env})

# Basic Sample programs
samples_env.SConscript('basic/SConscript', exports = {'env': samples_env})

# Simple Sample programs
samples_env.SConscript('simple/SConscript', exports = {'env': samples_env})

# Security Sample programs
samples_env.SConscript('secure/SConscript', exports = {'env': samples_env})

# Chat Sample program
samples_env.SConscript('chat/SConscript', exports = {'env': samples_env})

# File transfer Sample program
samples_env.SConscript('FileTransfer/SConscript', exports = {'env': samples_env})

# Sample Daemon program
samples_env.SConscript('SampleDaemon/SConscript', exports = {'env': samples_env})

# Event and Action Sample program
samples_env.SConscript('eventaction/SConscript', exports = {'env': samples_env})

# Install readme
if env['OS_CONF'] == 'windows':
    env.InstallAs('$CPP_DISTDIR/samples/README.txt', 'README.windows.txt')
elif env['OS_CONF'] == 'android':
    env.InstallAs('$CPP_DISTDIR/samples/README.txt', 'README.android.txt')
elif env['OS_CONF'] == 'linux':
    env.InstallAs('$CPP_DISTDIR/samples/README.txt', 'README.linux.txt')
