# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

Import('env')
clientDistDir = '$CPP_DISTDIR/samples/secure'

if env['OS_GROUP'] == 'windows':
    os_src = 'windows/ExclusiveFile.cc'
else:
    os_src = 'posix/ExclusiveFile.cc'

common_objs = [env.Object('ExclusiveFile', os_src), env.Object('CustomKeyStoreListener', 'CustomKeyStoreListener.cc')]

env1 = env.Clone();
env2 = env.Clone();
env1.Append(CPPDEFINES=[('CLIENT=1')])
env2.Append(CPPDEFINES=[('CLIENT=2')])

obj = env2.Object('DeskTopSharedKSClient2',  ['DeskTopSharedKSClient.cc'])

# Sample Programs
progs = [
    env.Program('DeskTopSharedKSService', [common_objs, 'DeskTopSharedKSService.cc']),
    env.Program('SampleServiceECDHE', ['SampleServiceECDHE.cc', 'SampleCertificateChainEngine.cc']),
    env.Program('SampleClientECDHE', ['SampleClientECDHE.cc', 'SampleCertificateChainEngine.cc']),
    env.Program('SampleCertificateUtility', ['SampleCertificateUtility.cc']),
    env1.Program('DeskTopSharedKSClient1',  [common_objs, 'DeskTopSharedKSClient.cc']),
    env2.Program('DeskTopSharedKSClient2',  [common_objs, obj])
    ]

# Door Sample
env.SConscript('door/SConscript', exports = {'env': env})

if env['OS'] != 'android':
     env.Install('$CPP_DISTDIR/bin/samples', progs )
     env.Install(clientDistDir, env.Glob('*.cc') + env.Glob('*.h'))