# Copyright AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 

Import('env')
clientDistDir = '$CPP_DISTDIR/samples/secure'
env1 = env.Clone();
env2 = env.Clone();
env_common = env.Clone()

# Temporary fix until ASACORE-2942 is resolved
env_common.Append(CPPPATH = [env['INCDIR_COMMON']])

env1.Append(CPPDEFINES=[('CLIENT=1')])
env2.Append(CPPDEFINES=[('CLIENT=2')])

obj_common = env_common.Object('CustomKeyStoreListener',  ['CustomKeyStoreListener.cc'])
obj = env2.Object('DeskTopSharedKSClient2',  ['DeskTopSharedKSClient.cc'])

# Sample Programs
progs = [
    env1.Program('DeskTopSharedKSClient1',  ['DeskTopSharedKSClient.cc', obj_common]),
    env2.Program('DeskTopSharedKSClient2',  [obj, obj_common]),
    env_common.Program('DeskTopSharedKSService', ['DeskTopSharedKSService.cc', obj_common]),
    env_common.Program('SampleServiceECDHE', ['SampleServiceECDHE.cc', 'SampleCertificateChainEngine.cc']),
    env_common.Program('SampleClientECDHE', ['SampleClientECDHE.cc', 'SampleCertificateChainEngine.cc']),
    env_common.Program('SampleCertificateUtility', ['SampleCertificateUtility.cc'])
    ]

# Door Sample
env_common.SConscript('door/SConscript', exports = {'env': env})

if env['OS'] != 'android':
     env_common.Install('$CPP_DISTDIR/bin/samples', progs )
     env_common.Install(clientDistDir, env.Glob('*.cc') + env.Glob('*.h'))
