# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

Import('env')

if '' != env.subst('$GECKO_BASE'):
    distdir = '$JS_DISTDIR/samples/%s'
else:
    distdir = '$JS_DISTDIR/samples/%s/assets/www'

# The return value is the collection of files installed in the build destination.
returnValue = []

for sample in ['addressbook/client',
               'addressbook/service',
               'chat',
               'props/client',
               'props/service',
               'simple/client',
               'simple/service']:
               #'streaming/sink',
               #'streaming/source']:
    env.Install(distdir % sample, env.Glob('%s/*' % sample))
    if '' != env.subst('$GECKO_BASE'):
        returnValue += env.Install(distdir % sample, '../js/npapi/alljoyn_init.js');
    else:
        returnValue += env.Install(distdir % sample, '../js/cordova/alljoyn_init.js');

for sample in ['simple/client',
               'simple/service']:
    returnValue += env.Install((distdir + '/js') % sample, 'simple/simple.js')
#for sample in ['streaming/sink',
#               'streaming/source']:
#    returnValue += env.Install((distdir + '/js') % sample, 'streaming/alljoyn.js')

Return('returnValue')