/******************************************************************************
 * Copyright (c) 2010 - 2014, AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for any
 *    purpose with or without fee is hereby granted, provided that the above
 *    copyright notice and this permission notice appear in all copies.
 *
 *    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#if defined(QCC_OS_GROUP_POSIX)
#undef JNIEXPORT
#define JNIEXPORT __attribute__((visibility("default")))
#endif
/* Header for class org_alljoyn_bus_BusAuthListener */

#ifndef _Included_org_alljoyn_bus_BusAuthListener
#define _Included_org_alljoyn_bus_BusAuthListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_BusAttachment */

#ifndef _Included_org_alljoyn_bus_BusAttachment
#define _Included_org_alljoyn_bus_BusAttachment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Lorg/alljoyn/bus/Variant;I)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_emitChangedSignal
  (JNIEnv *, jobject, jobject, jstring, jstring, jobject, jint);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    create
 * Signature: (Ljava/lang/String;ZI)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_create
  (JNIEnv *, jobject, jstring, jboolean, jint);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    connect
 * Signature: (Ljava/lang/String;Lorg/alljoyn/bus/KeyStoreListener;Ljava/lang/String;Lorg/alljoyn/bus/BusAttachment$AuthListenerInternal;Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_connect
  (JNIEnv *, jobject, jstring, jobject, jstring, jobject, jstring, jboolean);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_alljoyn_bus_BusAttachment_isConnected
  (JNIEnv *, jobject);


/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    disconnect
 * Signature: (Ljava/lang/String)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_disconnect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    requestName
 * Signature: (Ljava/lang/String;I)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_requestName
  (JNIEnv *, jobject,
   jstring, jint);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    releaseName
 * Signature: (Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_releaseName
  (JNIEnv *, jobject,
   jstring);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    addMatch
 * Signature: (Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_addMatch
  (JNIEnv *, jobject,
   jstring);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    removeMatch
 * Signature: (Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_removeMatch
  (JNIEnv *, jobject,
   jstring);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    advertiseName
 * Signature: (Ljava/lang/String;S)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_advertiseName
  (JNIEnv *, jobject,
   jstring, jshort);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    cancelAdvertiseName
 * Signature: (Ljava/lang/String;S)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_cancelAdvertiseName
  (JNIEnv *, jobject,
   jstring, jshort transports);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    findAdvertisedName
 * Signature: (Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_findAdvertisedName
  (JNIEnv *, jobject,
   jstring);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    findAdvertisedNameByTransport
 * Signature: (Ljava/lang/String;S)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_findAdvertisedNameByTransport
  (JNIEnv *, jobject,
   jstring, jshort);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    cancelFindAdvertiseName
 * Signature: (Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_cancelFindAdvertisedName
  (JNIEnv *, jobject,
   jstring);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    cancelFindAdvertiseNameByTransport
 * Signature: (Ljava/lang/String;S)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_cancelFindAdvertisedNameByTransport
  (JNIEnv *, jobject,
   jstring, jshort);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    bindSessionPort
 * Signature: (Lorg/alljoyn/bus/Mutable$ShortValue;Lorg/alljoyn/bus/SessionOpts;Lorg/alljoyn/bus/SessionPortListener;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_bindSessionPort
  (JNIEnv *, jobject,
   jobject, jobject, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    unbindSessionPort
 * Signature: (Lorg/alljoyn/bus/Mutable$ShortValue;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_unbindSessionPort
  (JNIEnv *, jobject,
   jshort);

/*
 * Class:     org_alljoyn_bus_SessionPortListener
 * Method:    create
 * Signature: (Lorg/alljoyn/bus/SessionPortListener;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_SessionPortListener_create
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_SessionPortListener
 * Method:    destroy
 * Signature: (Lorg/alljoyn/bus/SessionPortListener;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_SessionPortListener_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    joinSession
 * Signature: (Ljava/lang/String;SLorg/alljoyn/bus/Mutable/IntegerValue;Lorg/alljoyn/bus/SessionOpts;Lorg/alljoyn/bus/SessionListener;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_joinSession
  (JNIEnv *, jobject, jstring, jshort, jobject, jobject, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    leaveSession
 * Signature: (I)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_leaveSession
  (JNIEnv *, jobject,
   jint);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    leaveHostedSession
 * Signature: (I)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_leaveHostedSession
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    leaveJoinedSession
 * Signature: (I)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_leaveJoinedSession
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    removeSessionMember
 * Signature: (I;Ljava/lang/String)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_removeSessionMember
  (JNIEnv *, jobject,
   jint,jstring);

/*
 * Class:     org_alljoyn_bus_SessionListener
 * Method:    create
 * Signature: (Lorg/alljoyn/bus/SessionListener;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_SessionListener_create
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_SessionListener
 * Method:    destroy
 * Signature: (Lorg/alljoyn/bus/SessionListener;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_SessionListener_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    joinSessionAsync
 * Signature: (Ljava/lang/String;SLorg/alljoyn/bus/SessionOpts;Lorg/alljoyn/bus/SessionListener;Lorg/alljoyn/bus/BusAttachment/OnJoinSessionListener;Ljava/lang/Object;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_joinSessionAsync
(JNIEnv *, jobject, jstring, jshort, jobject, jobject, jobject, jobject);

/*
 * Class:     org_alljoyn_bus_OnJoinSessionListener
 * Method:    create
 * Signature: (Lorg/alljoyn/bus/OnJoinSessionListener;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_OnJoinSessionListener_create
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_OnJoinSessionListener
 * Method:    destroy
 * Signature: (Lorg/alljoyn/bus/OnJoinSessionListener;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_OnJoinSessionListener_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    setSessionListener
 * Signature: (ILorg/alljoyn/bus/SessionListener;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_setSessionListener
  (JNIEnv *, jobject,
   jint, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    setJoinedSessionListener
 * Signature: (ILorg/alljoyn/bus/SessionListener;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_setJoinedSessionListener
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    setHostedSessionListener
 * Signature: (ILorg/alljoyn/bus/SessionListener;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_setHostedSessionListener
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    getSessionFd
 * Signature: (ILorg/alljoyn/Mutable$IntegerValue;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_getSessionFd
  (JNIEnv *, jobject,
   jint, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    setLinkTimeout
 * Signature: (ILorg/alljoyn/Mutable$IntegerValue;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_setLinkTimeout
  (JNIEnv *, jobject,
   jint, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    getPeerGUID
 * Signature: (Ljava/lang/String;Lorg/alljoyn/Mutable$StringValue;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_getPeerGUID
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    ping
 * Signature: (Ljava/lang/String;I)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_ping
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    pingAsync
 * Signature: (Ljava/lang/String;ILorg/alljoyn/bus/OnPingListener;Ljava/lang/Object;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_pingAsync
  (JNIEnv *, jobject, jstring, jint, jobject, jobject);

/*
 * Class:     org_alljoyn_bus_OnPingListener
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_OnPingListener_create
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_OnPingListener
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_OnPingListener_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    setDaemonDebug
 * Signature: (Ljava/lang/String;I)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_setDaemonDebug
  (JNIEnv *, jobject,
   jstring, jint);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    setLogLevels
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_setLogLevels
  (JNIEnv *, jobject,
   jstring);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    setDebugLevel
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_setDebugLevel
  (JNIEnv *, jobject,
   jstring, jint);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    useOSLogging
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_useOSLogging
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    setAnnounceFlag
 * Signature: (Lorg/alljoyn/bus/BusObject;Ljava/lang/String;Z)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_setAnnounceFlag
  (JNIEnv *, jobject, jobject, jstring, jboolean);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    whoImplements
 * Signature: ([Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_whoImplements
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    cancelWhoImplements
 * Signature: ([Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_cancelWhoImplements
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    registerBusListener
 * Signature: (Lorg/alljoyn/bus/BusListener;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_registerBusListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    unregisterBusListener
 * Signature: (Lorg/alljoyn/bus/BusListener;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_unregisterBusListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_alljoyn_bus_BusListener
 * Method:    create
 * Signature: (Lorg/alljoyn/bus/BusListener;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusListener_create
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusListener
 * Method:    destroy
 * Signature: (Lorg/alljoyn/bus/BusListener;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusListener_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    enablePeerSecurity
 * Signature: (Ljava/lang/String;Lorg/alljoyn/bus/BusAttachment$AuthListenerInternal;Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL
Java_org_alljoyn_bus_BusAttachment_enablePeerSecurity
  (JNIEnv *env, jobject, jstring, jobject, jstring, jboolean);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    registerBusObject
 * Signature: (Ljava/lang/String;Lorg/alljoyn/bus/BusObject;[Lorg/alljoyn/bus/InterfaceDescription;Z)Lorg/alljoyn/bus/Status;Ljava/lang/String;Ljava/lang/String;Lorg/alljoyn/bus/Translator;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_registerBusObject
  (JNIEnv *, jobject, jstring, jobject, jobjectArray, jboolean, jstring, jstring, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    isSecureBusObject
 * Signature: (Lorg/alljoyn/bus/BusObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_alljoyn_bus_BusAttachment_isSecureBusObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    unregisterBusObject
 * Signature: (Lorg/alljoyn/bus/BusObject;)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_unregisterBusObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    registerNativeSignalHandlerWithSrcPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/reflect/Method;Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_registerNativeSignalHandlerWithSrcPath
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject, jstring);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    registerNativeSignalHandlerWithRule
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/reflect/Method;Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_registerNativeSignalHandlerWithRule
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject, jstring);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    unregisterSignalHandler
 * Signature: (Ljava/lang/Object;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_unregisterSignalHandler
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    getUniqueName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_getUniqueName
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    getGlobalGUIDString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_getGlobalGUIDString
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    clearKeyStore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_clearKeyStore
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    clearKeys
 * Signature: (Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_clearKeys
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    setKeyExpiration
 * Signature: (Ljava/lang/String;I)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_setKeyExpiration
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    getKeyExpiration
 * Signature: (Ljava/lang/String;Lorg/alljoyn/Mutable$StringValue;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_getKeyExpiration
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    reloadKeyStore
 * Signature: ()Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_reloadKeyStore
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    getMessageContext
 * Signature: ()Lorg/alljoyn/bus/MessageContext;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_BusAttachment_getMessageContext
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    enableConcurrentCallbacks
 * Signature: ()
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_enableConcurrentCallbacks
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_BusAttachment
 * Method:    setDescriptionTranslator
 * Signature: (Lorg/alljoyn/bus/Translator;)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusAttachment_setDescriptionTranslator
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_BusException */

#ifndef _Included_org_alljoyn_bus_BusException
#define _Included_org_alljoyn_bus_BusException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_alljoyn_bus_BusException_serialVersionUID
#define org_alljoyn_bus_BusException_serialVersionUID -3042686055658047285LL
#undef org_alljoyn_bus_BusException_serialVersionUID
#define org_alljoyn_bus_BusException_serialVersionUID -3387516993124229948LL
/*
 * Class:     org_alljoyn_bus_BusException
 * Method:    logln
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_BusException_logln
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_BusListener */

#ifndef _Included_org_alljoyn_bus_BusListener
#define _Included_org_alljoyn_bus_BusListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_Guid */

#ifndef _Included_org_alljoyn_bus_Guid
#define _Included_org_alljoyn_bus_Guid
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_InterfaceDescription */

#ifndef _Included_org_alljoyn_bus_InterfaceDescription
#define _Included_org_alljoyn_bus_InterfaceDescription
#ifdef __cplusplus
extern "C" {
#endif
#undef org_alljoyn_bus_InterfaceDescription_INVALID
#define org_alljoyn_bus_InterfaceDescription_INVALID 0L
#undef org_alljoyn_bus_InterfaceDescription_METHOD_CALL
#define org_alljoyn_bus_InterfaceDescription_METHOD_CALL 1L
#undef org_alljoyn_bus_InterfaceDescription_SIGNAL
#define org_alljoyn_bus_InterfaceDescription_SIGNAL 4L
#undef org_alljoyn_bus_InterfaceDescription_READ
#define org_alljoyn_bus_InterfaceDescription_READ 1L
#undef org_alljoyn_bus_InterfaceDescription_WRITE
#define org_alljoyn_bus_InterfaceDescription_WRITE 2L
#undef org_alljoyn_bus_InterfaceDescription_RW
#define org_alljoyn_bus_InterfaceDescription_RW 3L
#undef org_alljoyn_bus_InterfaceDescription_AJ_IFC_SECURITY_INHERIT
#define org_alljoyn_bus_InterfaceDescription_AJ_IFC_SECURITY_INHERIT 0L
#undef org_alljoyn_bus_InterfaceDescription_AJ_IFC_SECURITY_REQUIRED
#define org_alljoyn_bus_InterfaceDescription_AJ_IFC_SECURITY_REQUIRED 1L
#undef org_alljoyn_bus_InterfaceDescription_AJ_IFC_SECURITY_OFF
#define org_alljoyn_bus_InterfaceDescription_AJ_IFC_SECURITY_OFF 2L
/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    create
 * Signature: (Lorg/alljoyn/bus/BusAttachment;Ljava/lang/String;III)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_InterfaceDescription_create
  (JNIEnv *, jobject, jobject, jstring, jint, jint, jint);

/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    addMember
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_InterfaceDescription_addMember
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    addMemberAnnotation
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_InterfaceDescription_addMemberAnnotation
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    addProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_InterfaceDescription_addProperty
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    addPropertyAnnotation
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_InterfaceDescription_addPropertyAnnotation
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    addAnnotation
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_InterfaceDescription_addAnnotation
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    setDescriptionLanguage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_InterfaceDescription_setDescriptionLanguage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    setDescription
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_InterfaceDescription_setDescription
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    setDescriptionTranslator
 * Signature: (Lorg/alljoyn/bus/BusAttachment;Lorg/alljoyn/bus/Translator;)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_InterfaceDescription_setDescriptionTranslator
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    setMemberDescription
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_InterfaceDescription_setMemberDescription
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    setPropertyDescription
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_InterfaceDescription_setPropertyDescription
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_alljoyn_bus_InterfaceDescription
 * Method:    activate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_InterfaceDescription_activate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_InterfaceDescription_Property */

#ifndef _Included_org_alljoyn_bus_InterfaceDescription_Property
#define _Included_org_alljoyn_bus_InterfaceDescription_Property
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_BusObject */

#ifndef _Included_org_alljoyn_bus_BusObject
#define _Included_org_alljoyn_bus_BusObject
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_MessageContext */

#ifndef _Included_org_alljoyn_bus_MessageContext
#define _Included_org_alljoyn_bus_MessageContext
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_ProxyBusObject */

#ifndef _Included_org_alljoyn_bus_ProxyBusObject
#define _Included_org_alljoyn_bus_ProxyBusObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_alljoyn_bus_ProxyBusObject
 * Method:    create
 * Signature: (Lorg/alljoyn/bus/BusAttachment;Ljava/lang/String;Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_ProxyBusObject_create
(JNIEnv *, jobject, jobject, jstring, jstring, jint, jboolean);

/*
 * Class:     org_alljoyn_bus_ProxyBusObject
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_ProxyBusObject_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_ProxyBusObject
 * Method:    methodCall
 * Signature: (Lorg/alljoyn/bus/BusAttachment;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/reflect/Type;[Ljava/lang/Object;II)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_ProxyBusObject_methodCall
  (JNIEnv *, jobject, jobject, jstring, jstring, jstring, jobject, jobjectArray, jint, jint);

/*
 * Class:     org_alljoyn_bus_ProxyBusObject
 * Method:    getProperty
 * Signature: (Lorg/alljoyn/bus/BusAttachment;Ljava/lang/String;Ljava/lang/String;)Lorg/alljoyn/bus/Variant;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_ProxyBusObject_getProperty
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     org_alljoyn_bus_ProxyBusObject
 * Method:    getAllProperties
 * Signature: (Lorg/alljoyn/bus/BusAttachment;Ljava/lang/reflect/Type;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_ProxyBusObject_getAllProperties
  (JNIEnv *, jobject, jobject, jobject, jstring);
/*
 * Class:     org_alljoyn_bus_ProxyBusObject
 * Method:    setProperty
 * Signature: (Lorg/alljoyn/bus/BusAttachment;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_ProxyBusObject_setProperty
  (JNIEnv *, jobject, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     org_alljoyn_bus_ProxyBusObject
 * Method:    isProxyBusObjectSecure
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_alljoyn_bus_ProxyBusObject_isProxyBusObjectSecure
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_ProxyBusObject
 * Method:    registerPropertiesChangedListener
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Lorg/alljoyn/bus/PropertyChangedListener;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_ProxyBusObject_registerPropertiesChangedListener
  (JNIEnv *, jobject, jstring, jobjectArray, jobject);

/*
 * Class:     org_alljoyn_bus_ProxyBusObject
 * Method:    unregisterPropertiesChangedListener
 * Signature: (Ljava/lang/String;Lorg/alljoyn/bus/PropertyChangedListener;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_ProxyBusObject_unregisterPropertiesChangedListener
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif

/* Header for class org_alljoyn_bus_PropertiesChangedListener */

#ifndef _Included_org_alljoyn_bus_PropertiesChangedListener
#define _Included_org_alljoyn_bus_PropertiesChangedListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_alljoyn_bus_PropertiesChangedListener
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_PropertiesChangedListener_create
  (JNIEnv *, jobject, jobject, jobject);


/*
 * Class:     org_alljoyn_bus_PropertiesChangedListener
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_PropertiesChangedListener_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif


/* Header for class org_alljoyn_bus_ProxyBusObject_Handler */

#ifndef _Included_org_alljoyn_bus_ProxyBusObject_Handler
#define _Included_org_alljoyn_bus_ProxyBusObject_Handler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_SignalEmitter */

#ifndef _Included_org_alljoyn_bus_SignalEmitter
#define _Included_org_alljoyn_bus_SignalEmitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_alljoyn_bus_SignalEmitter
 * Method:    signal
 * Signature: (Lorg/alljoyn/bus/BusObject;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;IILorg/alljoyn/bus/MessageContext)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_SignalEmitter_signal
(JNIEnv *, jobject, jobject, jstring, jint, jstring, jstring, jstring, jobjectArray, jint, jint, jobject);

/*
 * Class:     org_alljoyn_bus_SignalEmitter
 * Method:    cancelSessionlessSignal
 * Signature: (Lorg/alljoyn/bus/BusObject;I)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_SignalEmitter_cancelSessionlessSignal
(JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_SignalEmitter_Emitter */

#ifndef _Included_org_alljoyn_bus_SignalEmitter_Emitter
#define _Included_org_alljoyn_bus_SignalEmitter_Emitter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_Signature */

#ifndef _Included_org_alljoyn_bus_Signature
#define _Included_org_alljoyn_bus_Signature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_alljoyn_bus_Signature
 * Method:    split
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_alljoyn_bus_Signature_split
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_Status */

#ifndef _Included_org_alljoyn_bus_Status
#define _Included_org_alljoyn_bus_Status
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_Variant */

#ifndef _Included_org_alljoyn_bus_Variant
#define _Included_org_alljoyn_bus_Variant
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_alljoyn_bus_Variant
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_Variant_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_Variant
 * Method:    setMsgArg
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_Variant_setMsgArg
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_annotation_BusInterface */

#ifndef _Included_org_alljoyn_bus_annotation_BusInterface
#define _Included_org_alljoyn_bus_annotation_BusInterface
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_annotation_BusMethod */

#ifndef _Included_org_alljoyn_bus_annotation_BusMethod
#define _Included_org_alljoyn_bus_annotation_BusMethod
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_annotation_BusSignal */

#ifndef _Included_org_alljoyn_bus_annotation_BusSignal
#define _Included_org_alljoyn_bus_annotation_BusSignal
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_annotation_BusSignalHandler */

#ifndef _Included_org_alljoyn_bus_annotation_BusSignalHandler
#define _Included_org_alljoyn_bus_annotation_BusSignalHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_annotation_Position */

#ifndef _Included_org_alljoyn_bus_annotation_Position
#define _Included_org_alljoyn_bus_annotation_Position
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_annotation_Secure */

#ifndef _Included_org_alljoyn_bus_annotation_Secure
#define _Included_org_alljoyn_bus_annotation_Secure
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_annotation_Signature */

#ifndef _Included_org_alljoyn_bus_annotation_Signature
#define _Included_org_alljoyn_bus_annotation_Signature
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_ifaces_DBusProxyObj */

#ifndef _Included_org_alljoyn_bus_ifaces_DBusProxyObj
#define _Included_org_alljoyn_bus_ifaces_DBusProxyObj
#ifdef __cplusplus
extern "C" {
#endif
#undef org_alljoyn_bus_ifaces_DBusProxyObj_REQUEST_NAME_ALLOW_REPLACEMENT
#define org_alljoyn_bus_ifaces_DBusProxyObj_REQUEST_NAME_ALLOW_REPLACEMENT 1L
#undef org_alljoyn_bus_ifaces_DBusProxyObj_REQUEST_NAME_REPLACE_EXISTING
#define org_alljoyn_bus_ifaces_DBusProxyObj_REQUEST_NAME_REPLACE_EXISTING 2L
#undef org_alljoyn_bus_ifaces_DBusProxyObj_REQUEST_NAME_DO_NOT_QUEUE
#define org_alljoyn_bus_ifaces_DBusProxyObj_REQUEST_NAME_DO_NOT_QUEUE 4L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_ifaces_DBusProxyObj_ReleaseNameResult */

#ifndef _Included_org_alljoyn_bus_ifaces_DBusProxyObj_ReleaseNameResult
#define _Included_org_alljoyn_bus_ifaces_DBusProxyObj_ReleaseNameResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_ifaces_DBusProxyObj_RequestNameResult */

#ifndef _Included_org_alljoyn_bus_ifaces_DBusProxyObj_RequestNameResult
#define _Included_org_alljoyn_bus_ifaces_DBusProxyObj_RequestNameResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_ifaces_Introspectable */

#ifndef _Included_org_alljoyn_bus_ifaces_Introspectable
#define _Included_org_alljoyn_bus_ifaces_Introspectable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_ifaces_AllJoynProxyObj */

#ifndef _Included_org_alljoyn_bus_ifaces_AllJoynProxyObj
#define _Included_org_alljoyn_bus_ifaces_AllJoynProxyObj
#ifdef __cplusplus
extern "C" {
#endif
#undef org_alljoyn_bus_ifaces_AllJoynProxyObj_REQUEST_NAME_ALLOW_REPLACEMENT
#define org_alljoyn_bus_ifaces_AllJoynProxyObj_REQUEST_NAME_ALLOW_REPLACEMENT 1L
#undef org_alljoyn_bus_ifaces_AllJoynProxyObj_REQUEST_NAME_REPLACE_EXISTING
#define org_alljoyn_bus_ifaces_AllJoynProxyObj_REQUEST_NAME_REPLACE_EXISTING 2L
#undef org_alljoyn_bus_ifaces_AllJoynProxyObj_REQUEST_NAME_DO_NOT_QUEUE
#define org_alljoyn_bus_ifaces_AllJoynProxyObj_REQUEST_NAME_DO_NOT_QUEUE 4L
#undef org_alljoyn_bus_ifaces_AllJoynProxyObj_REQUEST_NAME_EXPORTABLE
#define org_alljoyn_bus_ifaces_AllJoynProxyObj_REQUEST_NAME_EXPORTABLE 8L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_ifaces_AllJoynProxyObj_ReleaseNameResult */

#ifndef _Included_org_alljoyn_bus_ifaces_AllJoynProxyObj_ReleaseNameResult
#define _Included_org_alljoyn_bus_ifaces_AllJoynProxyObj_ReleaseNameResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_ifaces_AllJoynProxyObj_RequestNameResult */

#ifndef _Included_org_alljoyn_bus_ifaces_AllJoynProxyObj_RequestNameResult
#define _Included_org_alljoyn_bus_ifaces_AllJoynProxyObj_RequestNameResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_ifaces_Peer */

#ifndef _Included_org_alljoyn_bus_ifaces_Peer
#define _Included_org_alljoyn_bus_ifaces_Peer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_ifaces_Properties */

#ifndef _Included_org_alljoyn_bus_ifaces_Properties
#define _Included_org_alljoyn_bus_ifaces_Properties
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_alljoyn_bus_MsgArg */

#ifndef _Included_org_alljoyn_bus_MsgArg
#define _Included_org_alljoyn_bus_MsgArg
#ifdef __cplusplus
extern "C" {
#endif
#undef org_alljoyn_bus_MsgArg_ALLJOYN_INVALID
#define org_alljoyn_bus_MsgArg_ALLJOYN_INVALID 0L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_ARRAY
#define org_alljoyn_bus_MsgArg_ALLJOYN_ARRAY 97L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_BOOLEAN
#define org_alljoyn_bus_MsgArg_ALLJOYN_BOOLEAN 98L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_DOUBLE
#define org_alljoyn_bus_MsgArg_ALLJOYN_DOUBLE 100L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_DICT_ENTRY
#define org_alljoyn_bus_MsgArg_ALLJOYN_DICT_ENTRY 101L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_SIGNATURE
#define org_alljoyn_bus_MsgArg_ALLJOYN_SIGNATURE 103L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_INT32
#define org_alljoyn_bus_MsgArg_ALLJOYN_INT32 105L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_INT16
#define org_alljoyn_bus_MsgArg_ALLJOYN_INT16 110L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_OBJECT_PATH
#define org_alljoyn_bus_MsgArg_ALLJOYN_OBJECT_PATH 111L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_UINT16
#define org_alljoyn_bus_MsgArg_ALLJOYN_UINT16 113L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_STRUCT
#define org_alljoyn_bus_MsgArg_ALLJOYN_STRUCT 114L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_STRING
#define org_alljoyn_bus_MsgArg_ALLJOYN_STRING 115L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_UINT64
#define org_alljoyn_bus_MsgArg_ALLJOYN_UINT64 116L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_UINT32
#define org_alljoyn_bus_MsgArg_ALLJOYN_UINT32 117L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_VARIANT
#define org_alljoyn_bus_MsgArg_ALLJOYN_VARIANT 118L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_INT64
#define org_alljoyn_bus_MsgArg_ALLJOYN_INT64 120L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_BYTE
#define org_alljoyn_bus_MsgArg_ALLJOYN_BYTE 121L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_STRUCT_OPEN
#define org_alljoyn_bus_MsgArg_ALLJOYN_STRUCT_OPEN 40L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_STRUCT_CLOSE
#define org_alljoyn_bus_MsgArg_ALLJOYN_STRUCT_CLOSE 41L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_DICT_ENTRY_OPEN
#define org_alljoyn_bus_MsgArg_ALLJOYN_DICT_ENTRY_OPEN 123L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_DICT_ENTRY_CLOSE
#define org_alljoyn_bus_MsgArg_ALLJOYN_DICT_ENTRY_CLOSE 125L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_BOOLEAN_ARRAY
#define org_alljoyn_bus_MsgArg_ALLJOYN_BOOLEAN_ARRAY 25185L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_DOUBLE_ARRAY
#define org_alljoyn_bus_MsgArg_ALLJOYN_DOUBLE_ARRAY 25697L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_INT32_ARRAY
#define org_alljoyn_bus_MsgArg_ALLJOYN_INT32_ARRAY 26977L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_INT16_ARRAY
#define org_alljoyn_bus_MsgArg_ALLJOYN_INT16_ARRAY 28257L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_UINT16_ARRAY
#define org_alljoyn_bus_MsgArg_ALLJOYN_UINT16_ARRAY 29025L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_UINT64_ARRAY
#define org_alljoyn_bus_MsgArg_ALLJOYN_UINT64_ARRAY 29793L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_UINT32_ARRAY
#define org_alljoyn_bus_MsgArg_ALLJOYN_UINT32_ARRAY 30049L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_INT64_ARRAY
#define org_alljoyn_bus_MsgArg_ALLJOYN_INT64_ARRAY 30817L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_BYTE_ARRAY
#define org_alljoyn_bus_MsgArg_ALLJOYN_BYTE_ARRAY 31073L
#undef org_alljoyn_bus_MsgArg_ALLJOYN_WILDCARD
#define org_alljoyn_bus_MsgArg_ALLJOYN_WILDCARD 42L
/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getNumElements
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_alljoyn_bus_MsgArg_getNumElements
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getElement
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_getElement
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getElemSig
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_alljoyn_bus_MsgArg_getElemSig
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getVal
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_getVal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getNumMembers
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_alljoyn_bus_MsgArg_getNumMembers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getMember
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_getMember
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getKey
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_getKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getByteArray
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_alljoyn_bus_MsgArg_getByteArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getInt16Array
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_org_alljoyn_bus_MsgArg_getInt16Array
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getUint16Array
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_org_alljoyn_bus_MsgArg_getUint16Array
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getBoolArray
 * Signature: (J)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_org_alljoyn_bus_MsgArg_getBoolArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getUint32Array
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_org_alljoyn_bus_MsgArg_getUint32Array
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getInt32Array
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_org_alljoyn_bus_MsgArg_getInt32Array
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getInt64Array
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_alljoyn_bus_MsgArg_getInt64Array
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getUint64Array
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_alljoyn_bus_MsgArg_getUint64Array
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getDoubleArray
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_alljoyn_bus_MsgArg_getDoubleArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getTypeId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_alljoyn_bus_MsgArg_getTypeId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_alljoyn_bus_MsgArg_getByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getInt16
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_org_alljoyn_bus_MsgArg_getInt16
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getUint16
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_org_alljoyn_bus_MsgArg_getUint16
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getBool
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_alljoyn_bus_MsgArg_getBool
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getUint32
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_alljoyn_bus_MsgArg_getUint32
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getInt32
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_alljoyn_bus_MsgArg_getInt32
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getInt64
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_getInt64
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getUint64
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_getUint64
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_alljoyn_bus_MsgArg_getDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_alljoyn_bus_MsgArg_getString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getObjPath
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_alljoyn_bus_MsgArg_getObjPath
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getSignature
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_alljoyn_bus_MsgArg_getSignature__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    getSignature
 * Signature: ([J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_alljoyn_bus_MsgArg_getSignature___3J
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;B)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2B
  (JNIEnv *, jclass, jlong, jstring, jbyte);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2Z
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;S)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2S
  (JNIEnv *, jclass, jlong, jstring, jshort);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2I
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2J
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;D)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2D
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;[B)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2_3B
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;[Z)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2_3Z
  (JNIEnv *, jclass, jlong, jstring, jbooleanArray);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;[S)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2_3S
  (JNIEnv *, jclass, jlong, jstring, jshortArray);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;[I)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2_3I
  (JNIEnv *, jclass, jlong, jstring, jintArray);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;[J)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2_3J
  (JNIEnv *, jclass, jlong, jstring, jlongArray);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    set
 * Signature: (JLjava/lang/String;[D)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_set__JLjava_lang_String_2_3D
  (JNIEnv *, jclass, jlong, jstring, jdoubleArray);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    setArray
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_setArray
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    setStruct
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_setStruct
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    setDictEntry
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_setDictEntry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    setVariant
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_setVariant__JLjava_lang_String_2J
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_alljoyn_bus_MsgArg
 * Method:    setVariant
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_alljoyn_bus_MsgArg_setVariant__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_alljoyn_bus_PasswordManager
 * Method:    setCredentials
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_PasswordManager_setCredentials
  (JNIEnv *, jobject,
   jstring, jstring);

/*
 * Class:     org_alljoyn_bus_Translator
 * Method:    create
 * Signature: (Lorg/alljoyn/bus/Translator;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_Translator_create
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_Translator
 * Method:    destroy
 * Signature: (Lorg/alljoyn/bus/Translator;)V;
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_Translator_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_AboutObj
 * Method:    create
 * Signature: (Lorg/alljoyn/bus/BusAttachment;Z)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_AboutObj_create
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_alljoyn_bus_AboutObj
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_bus_AboutObj_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_AboutObj
 * Method:    announce
 * Signature: (SLorg/alljoyn/bus/AboutDataListener;)Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_AboutObj_announce
  (JNIEnv *, jobject, jshort, jobject);

/*
 * Class:     org_alljoyn_bus_AboutObj
 * Method:    unannounce
 * Signature: ()Lorg/alljoyn/bus/Status;
 */
JNIEXPORT jobject JNICALL Java_org_alljoyn_bus_AboutObj_unannounce
  (JNIEnv *, jobject);

/*
 * Class:     org_alljoyn_bus_Version
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_alljoyn_bus_Version_get
  (JNIEnv *, jclass);

/*
 * Class:     org_alljoyn_bus_Version
 * Method:    getBuildInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_alljoyn_bus_Version_getBuildInfo
  (JNIEnv *, jclass);

/*
 * Class:     org_alljoyn_bus_Version
 * Method:    getNumeric
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_alljoyn_bus_Version_getNumeric
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
