# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#

Import('env')

# JNI library sources
srcs = env.Glob('*.cc')

# JNI library
bdenv = env.Clone()

if bdenv['LIBTYPE'] == 'both':
    # Need to replace the shared alljoyn library with the static one for linking the plugin.
    libs = bdenv['LIBS']
    libs[libs.index('alljoyn')] = bdenv.File('$DISTDIR/cpp/lib/${LIBPREFIX}alljoyn${LIBSUFFIX}')
    bdenv.Replace(LIBS = libs)

# The JNI code must link in the bundled daemon even if BR is set to 'off'
if bdenv['BR'] == 'on':
    bdenv.Prepend(LIBS = [env['ajrlib']])

objs = bdenv.SharedObject(srcs)

liballjoyn_java = bdenv.SharedLibrary('alljoyn_java', objs)

Return('liballjoyn_java')