# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

Import('env')

# The return value is the collection of files installed in the build destination.
returnValue = env.Install('$JAVA_DISTDIR/samples', 'README.txt')

returnValue += env.SConscript('JavaSDKDoc/SConscript', exports = ['env'])

Return('returnValue')