# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('sample_env')

sample_env.Append(JAVACFLAGS = ['-encoding', 'UTF-8'])
classes = sample_env.Java(sample_env.Dir('$OBJDIR_ABOUT/java/samples/classes').srcnode(), 'src', JAVAVERSION='1.6')
sample_env.Depends(classes, sample_env['dep_jars'])
classes.append('MANIFEST.MF') 

jar = sample_env.Jar(target = 'about_server_sample_legacy', source = classes)

Return('jar')
