# Copyright (c) 2013, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('about_env')
import os

# Sources
srcs = about_env.Glob('*.cc')

# Platform specific sources
if about_env['OS'] == 'android':
    srcs += about_env.Glob('$OS/*.cc')
else:
    srcs += about_env.Glob('$OS_GROUP/*.cc')

libs = []

# Static library
objs = about_env.Object(srcs)
libs.append(about_env.StaticLibrary('alljoyn_about', objs))

# Shared library
if about_env.get('LIBTYPE', 'static') != 'static':
    shobjs = about_env.SharedObject(srcs)
    libs.append(about_env.SharedLibrary('alljoyn_about', shobjs))

Return ('libs')
