# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('config_env')

if config_env['OS_CONF'] in ['linux', 'openwrt', 'windows']:
    local_env = config_env.Clone()

    local_env.Prepend(LIBS = ['alljoyn_config', 'alljoyn_about' ])

    if local_env['OS_GROUP'] == 'posix':
        local_env.Append(CXXFLAGS = ['-Wno-deprecated-declarations'])
    if local_env['OS_GROUP'] == 'windows':
        local_env.Append(CXXFLAGS = ['/wd4996'])

    if local_env['BR'] == 'on' and local_env.has_key('ajrlib'):
        # Build apps with bundled daemon support
        local_env.Prepend(LIBS = [local_env['ajrlib']])

    # Sample programs
    sample_dirs = [
        'ConfigClientSample',
        'ConfigServiceSample'
        ]

    exports = { 'env': local_env }
    progs = [ local_env.SConscript('%s/SConscript' % sampleapp, exports = exports) for sampleapp in sample_dirs ]

else:
    progs = []

Return('progs')