# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('config_env')

classes = config_env.Java('$OBJDIR_CONFIG/java/classes', source = ['org'])
if config_env['dep_jars']:
    config_env.Depends(classes, config_env['dep_jars'])
jars = config_env.Jar(target = 'alljoyn_config', source = classes)

Return('jars')