# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('env')

# External libs
env.SConscript('external/SConscript', exports = {'env': env})

# Security Manager Agent lib
env.SConscript('agent/SConscript', exports = {'env': env})

# Security Manager Storage lib
env.SConscript('storage/SConscript', exports = {'env': env})

# Secmgr app
env.SConscript('cli/SConscript', exports = {'env': env})