# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#
import os
import difflib

Import('env')

jsdocenv = env.Clone()

vars = Variables()
vars.Add(PathVariable('JSDOC_DIR', 'The path to the JsDoc toolkit', os.environ.get('JSDOC_DIR'), PathVariable.PathIsDir))
vars.Update(jsdocenv)
Help(vars.GenerateHelpText(jsdocenv))

if jsdocenv.has_key('JSDOC_DIR'):
    jsdocenv.PrependENVPath('PATH', jsdocenv.get('JSDOC_DIR'))

# Build docs
if jsdocenv.has_key('JSDOC_DIR'):
    jsdocenv['JSDOC_TEMPLATE'] = jsdocenv.Dir('$JSDOC_DIR/templates/default')
    doc_out = jsdocenv.jsdoc3(target=[jsdocenv.Dir('html')], source=['alljoyn_doc'])
    documentation = jsdocenv.Install('$JS_DISTDIR/docs', 'html')