# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('env')

app_env = env.Clone()
app_env.Prepend(LIBS = ['alljoyn'])
app_env.Append(CPPPATH = [env['INCDIR_COMMON']])

# Sample Programs
progs = [
    app_env.Program('SecureDoorProvider', ['secure_door_provider.cc', 'secure_door_common.cc']),
    app_env.Program('SecureDoorConsumer', ['secure_door_consumer.cc', 'secure_door_common.cc']),
    ]

clientDistDir = '$CPP_DISTDIR/samples/secure/door'

if env['OS'] != 'android':
     app_env.Install('$CPP_DISTDIR/bin/samples', progs )
     app_env.Install(clientDistDir, env.Glob('*.cc') + env.Glob('*.h'))