# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

import os
Import('env')

docenv = env.Clone()
docenv['ENV']['C_DISTDIR'] = str(env.Dir('$C_DISTDIR'))

# Build docs
installDocs = []
if docenv['DOCS'] == 'html':
    installDocs = docenv.Doxygen(source='Doxygen_html')

# Build Alias to make cleaning, building and rebuilding the documentation when
# working only on the documentation simpler. This can be run by using
# `scons c_docs`
docenv.Alias('c_docs', installDocs)

Return('installDocs')