# Copyright (c) 2013, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

import os

# include the core
env = SConscript(['../build_core/SConscript'])

# If building the the common project without building alljoyn_core status.h/.cc
# will not be built typically because the status.h/.cc file will be built from
# the alljoyn_core project and will include more status parameters.
# the BUILD_COMMON_STATUS should only be defined if building common project only
vars = Variables()
vars.Add('BUILD_COMMON_STATUS', 'When building the common build status.h and status.cc using the status.xml from common', '1')
vars.Update(env)

# Add/remove projects from build
env.SConscript(['SConscript'])


