# Copyright (c) 2013-2014, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('about_env')

sample_env = about_env.Clone()

sample_env.Append(JAVACLASSPATH = str(about_env.File('$DISTDIR/java/jar/alljoyn_about.jar')))
sample_env['dep_jars'].append('$DISTDIR/java/jar/alljoyn_about.jar')

if sample_env['OS'] == 'linux' or sample_env['OS_GROUP'] == 'windows':
    jars = sample_env.SConscript('java/SConscript', exports = ['sample_env'])
else:
    jars = []

Return('jars')
