/* This file is auto-generated.  Do not modify. */
/*
 * Copyright (c) 2011-2013, AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for any
 *    purpose with or without fee is hereby granted, provided that the above
 *    copyright notice and this permission notice appear in all copies.
 *
 *    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#include "BusErrorInterface.h"

#include "TypeMapping.h"
#include <qcc/Debug.h>

#define QCC_MODULE "ALLJOYN_JS"

std::map<qcc::String, int32_t> _BusErrorInterface::constants;

std::map<qcc::String, int32_t>& _BusErrorInterface::Constants()
{
    if (constants.empty()) {
        CONSTANT("OK", 0x0);
        CONSTANT("FAIL", 0x1);
        CONSTANT("UTF_CONVERSION_FAILED", 0x2);
        CONSTANT("BUFFER_TOO_SMALL", 0x3);
        CONSTANT("OS_ERROR", 0x4);
        CONSTANT("OUT_OF_MEMORY", 0x5);
        CONSTANT("SOCKET_BIND_ERROR", 0x6);
        CONSTANT("INIT_FAILED", 0x7);
        CONSTANT("WOULDBLOCK", 0x8);
        CONSTANT("NOT_IMPLEMENTED", 0x9);
        CONSTANT("TIMEOUT", 0xa);
        CONSTANT("SOCK_OTHER_END_CLOSED", 0xb);
        CONSTANT("BAD_ARG_1", 0xc);
        CONSTANT("BAD_ARG_2", 0xd);
        CONSTANT("BAD_ARG_3", 0xe);
        CONSTANT("BAD_ARG_4", 0xf);
        CONSTANT("BAD_ARG_5", 0x10);
        CONSTANT("BAD_ARG_6", 0x11);
        CONSTANT("BAD_ARG_7", 0x12);
        CONSTANT("BAD_ARG_8", 0x13);
        CONSTANT("INVALID_ADDRESS", 0x14);
        CONSTANT("INVALID_DATA", 0x15);
        CONSTANT("READ_ERROR", 0x16);
        CONSTANT("WRITE_ERROR", 0x17);
        CONSTANT("OPEN_FAILED", 0x18);
        CONSTANT("PARSE_ERROR", 0x19);
        CONSTANT("END_OF_DATA", 0x1A);
        CONSTANT("CONN_REFUSED", 0x1B);
        CONSTANT("BAD_ARG_COUNT", 0x1C);
        CONSTANT("WARNING", 0x1D);
        CONSTANT("COMMON_ERRORS", 0x1000);
        CONSTANT("STOPPING_THREAD", 0x1001);
        CONSTANT("ALERTED_THREAD", 0x1002);
        CONSTANT("XML_MALFORMED", 0x1003);
        CONSTANT("AUTH_FAIL", 0x1004);
        CONSTANT("AUTH_USER_REJECT", 0x1005);
        CONSTANT("NO_SUCH_ALARM", 0x1006);
        CONSTANT("TIMER_FALLBEHIND", 0x1007);
        CONSTANT("SSL_ERRORS", 0x1008);
        CONSTANT("SSL_INIT", 0x1009);
        CONSTANT("SSL_CONNECT", 0x100a);
        CONSTANT("SSL_VERIFY", 0x100b);
        CONSTANT("EXTERNAL_THREAD", 0x100c);
        CONSTANT("CRYPTO_ERROR", 0x100d);
        CONSTANT("CRYPTO_TRUNCATED", 0x100e);
        CONSTANT("CRYPTO_KEY_UNAVAILABLE", 0x100f);
        CONSTANT("BAD_HOSTNAME", 0x1010);
        CONSTANT("CRYPTO_KEY_UNUSABLE", 0x1011);
        CONSTANT("EMPTY_KEY_BLOB", 0x1012);
        CONSTANT("CORRUPT_KEYBLOB", 0x1013);
        CONSTANT("INVALID_KEY_ENCODING", 0x1014);
        CONSTANT("DEAD_THREAD", 0x1015);
        CONSTANT("THREAD_RUNNING", 0x1016);
        CONSTANT("THREAD_STOPPING", 0x1017);
        CONSTANT("BAD_STRING_ENCODING", 0x1018);
        CONSTANT("CRYPTO_INSUFFICIENT_SECURITY", 0x1019);
        CONSTANT("CRYPTO_ILLEGAL_PARAMETERS", 0x101a);
        CONSTANT("CRYPTO_HASH_UNINITIALIZED", 0x101b);
        CONSTANT("THREAD_NO_WAIT", 0x101c);
        CONSTANT("TIMER_EXITING", 0x101d);
        CONSTANT("INVALID_GUID", 0x101e);
        CONSTANT("THREADPOOL_EXHAUSTED", 0x101f);
        CONSTANT("THREADPOOL_STOPPING", 0x1020);
        CONSTANT("INVALID_STREAM", 0x1021);
        CONSTANT("TIMER_FULL", 0x1022);
        CONSTANT("IODISPATCH_STOPPING", 0x1023);
        CONSTANT("SLAP_INVALID_PACKET_LEN", 0x1024);
        CONSTANT("SLAP_HDR_CHECKSUM_ERROR", 0x1025);
        CONSTANT("SLAP_INVALID_PACKET_TYPE", 0x1026);
        CONSTANT("SLAP_LEN_MISMATCH", 0x1027);
        CONSTANT("SLAP_PACKET_TYPE_MISMATCH", 0x1028);
        CONSTANT("SLAP_CRC_ERROR", 0x1029);
        CONSTANT("SLAP_ERROR", 0x102A);
        CONSTANT("SLAP_OTHER_END_CLOSED", 0x102B);
        CONSTANT("NONE", 0xffff);
        CONSTANT("BUS_ERRORS", 0x9000);
        CONSTANT("BUS_READ_ERROR", 0x9001);
        CONSTANT("BUS_WRITE_ERROR", 0x9002);
        CONSTANT("BUS_BAD_VALUE_TYPE", 0x9003);
        CONSTANT("BUS_BAD_HEADER_FIELD", 0x9004);
        CONSTANT("BUS_BAD_SIGNATURE", 0x9005);
        CONSTANT("BUS_BAD_OBJ_PATH", 0x9006);
        CONSTANT("BUS_BAD_MEMBER_NAME", 0x9007);
        CONSTANT("BUS_BAD_INTERFACE_NAME", 0x9008);
        CONSTANT("BUS_BAD_ERROR_NAME", 0x9009);
        CONSTANT("BUS_BAD_BUS_NAME", 0x900a);
        CONSTANT("BUS_NAME_TOO_LONG", 0x900b);
        CONSTANT("BUS_BAD_LENGTH", 0x900c);
        CONSTANT("BUS_BAD_VALUE", 0x900d);
        CONSTANT("BUS_BAD_HDR_FLAGS", 0x900e);
        CONSTANT("BUS_BAD_BODY_LEN", 0x900f);
        CONSTANT("BUS_BAD_HEADER_LEN", 0x9010);
        CONSTANT("BUS_UNKNOWN_SERIAL", 0x9011);
        CONSTANT("BUS_UNKNOWN_PATH", 0x9012);
        CONSTANT("BUS_UNKNOWN_INTERFACE", 0x9013);
        CONSTANT("BUS_ESTABLISH_FAILED", 0x9014);
        CONSTANT("BUS_UNEXPECTED_SIGNATURE", 0x9015);
        CONSTANT("BUS_INTERFACE_MISSING", 0x9016);
        CONSTANT("BUS_PATH_MISSING", 0x9017);
        CONSTANT("BUS_MEMBER_MISSING", 0x9018);
        CONSTANT("BUS_REPLY_SERIAL_MISSING", 0x9019);
        CONSTANT("BUS_ERROR_NAME_MISSING", 0x901a);
        CONSTANT("BUS_INTERFACE_NO_SUCH_MEMBER", 0x901b);
        CONSTANT("BUS_NO_SUCH_OBJECT", 0x901c);
        CONSTANT("BUS_OBJECT_NO_SUCH_MEMBER", 0x901d);
        CONSTANT("BUS_OBJECT_NO_SUCH_INTERFACE", 0x901e);
        CONSTANT("BUS_NO_SUCH_INTERFACE", 0x901f);
        CONSTANT("BUS_MEMBER_NO_SUCH_SIGNATURE", 0x9020);
        CONSTANT("BUS_NOT_NUL_TERMINATED", 0x9021);
        CONSTANT("BUS_NO_SUCH_PROPERTY", 0x9022);
        CONSTANT("BUS_SET_WRONG_SIGNATURE", 0x9023);
        CONSTANT("BUS_PROPERTY_VALUE_NOT_SET", 0x9024);
        CONSTANT("BUS_PROPERTY_ACCESS_DENIED", 0x9025);
        CONSTANT("BUS_NO_TRANSPORTS", 0x9026);
        CONSTANT("BUS_BAD_TRANSPORT_ARGS", 0x9027);
        CONSTANT("BUS_NO_ROUTE", 0x9028);
        CONSTANT("BUS_NO_ENDPOINT", 0x9029);
        CONSTANT("BUS_BAD_SEND_PARAMETER", 0x902a);
        CONSTANT("BUS_UNMATCHED_REPLY_SERIAL", 0x902b);
        CONSTANT("BUS_BAD_SENDER_ID", 0x902c);
        CONSTANT("BUS_TRANSPORT_NOT_STARTED", 0x902d);
        CONSTANT("BUS_EMPTY_MESSAGE", 0x902e);
        CONSTANT("BUS_NOT_OWNER", 0x902f);
        CONSTANT("BUS_SET_PROPERTY_REJECTED", 0x9030);
        CONSTANT("BUS_CONNECT_FAILED", 0x9031);
        CONSTANT("BUS_REPLY_IS_ERROR_MESSAGE", 0x9032);
        CONSTANT("BUS_NOT_AUTHENTICATING", 0x9033);
        CONSTANT("BUS_NO_LISTENER", 0x9034);
        CONSTANT("BUS_BT_TRANSPORT_ERROR", 0x9035);
        CONSTANT("BUS_NOT_ALLOWED", 0x9036);
        CONSTANT("BUS_WRITE_QUEUE_FULL", 0x9037);
        CONSTANT("BUS_ENDPOINT_CLOSING", 0x9038);
        CONSTANT("BUS_INTERFACE_MISMATCH", 0x9039);
        CONSTANT("BUS_MEMBER_ALREADY_EXISTS", 0x903a);
        CONSTANT("BUS_PROPERTY_ALREADY_EXISTS", 0x903b);
        CONSTANT("BUS_IFACE_ALREADY_EXISTS", 0x903c);
        CONSTANT("BUS_ERROR_RESPONSE", 0x903d);
        CONSTANT("BUS_BAD_XML", 0x903e);
        CONSTANT("BUS_BAD_CHILD_PATH", 0x903f);
        CONSTANT("BUS_OBJ_ALREADY_EXISTS", 0x9040);
        CONSTANT("BUS_OBJ_NOT_FOUND", 0x9041);
        CONSTANT("BUS_CANNOT_EXPAND_MESSAGE", 0x9042);
        CONSTANT("BUS_NOT_COMPRESSED", 0x9043);
        CONSTANT("BUS_ALREADY_CONNECTED", 0x9044);
        CONSTANT("BUS_NOT_CONNECTED", 0x9045);
        CONSTANT("BUS_ALREADY_LISTENING", 0x9046);
        CONSTANT("BUS_KEY_UNAVAILABLE", 0x9047);
        CONSTANT("BUS_TRUNCATED", 0x9048);
        CONSTANT("BUS_KEY_STORE_NOT_LOADED", 0x9049);
        CONSTANT("BUS_NO_AUTHENTICATION_MECHANISM", 0x904a);
        CONSTANT("BUS_BUS_ALREADY_STARTED", 0x904b);
        CONSTANT("BUS_BUS_NOT_STARTED", 0x904c);
        CONSTANT("BUS_KEYBLOB_OP_INVALID", 0x904d);
        CONSTANT("BUS_INVALID_HEADER_CHECKSUM", 0x904e);
        CONSTANT("BUS_MESSAGE_NOT_ENCRYPTED", 0x904f);
        CONSTANT("BUS_INVALID_HEADER_SERIAL", 0x9050);
        CONSTANT("BUS_TIME_TO_LIVE_EXPIRED", 0x9051);
        CONSTANT("BUS_HDR_EXPANSION_INVALID", 0x9052);
        CONSTANT("BUS_MISSING_COMPRESSION_TOKEN", 0x9053);
        CONSTANT("BUS_NO_PEER_GUID", 0x9054);
        CONSTANT("BUS_MESSAGE_DECRYPTION_FAILED", 0x9055);
        CONSTANT("BUS_SECURITY_FATAL", 0x9056);
        CONSTANT("BUS_KEY_EXPIRED", 0x9057);
        CONSTANT("BUS_CORRUPT_KEYSTORE", 0x9058);
        CONSTANT("BUS_NO_CALL_FOR_REPLY", 0x9059);
        CONSTANT("BUS_NOT_A_COMPLETE_TYPE", 0x905a);
        CONSTANT("BUS_POLICY_VIOLATION", 0x905b);
        CONSTANT("BUS_NO_SUCH_SERVICE", 0x905c);
        CONSTANT("BUS_TRANSPORT_NOT_AVAILABLE", 0x905d);
        CONSTANT("BUS_INVALID_AUTH_MECHANISM", 0x905e);
        CONSTANT("BUS_KEYSTORE_VERSION_MISMATCH", 0x905f);
        CONSTANT("BUS_BLOCKING_CALL_NOT_ALLOWED", 0x9060);
        CONSTANT("BUS_SIGNATURE_MISMATCH", 0x9061);
        CONSTANT("BUS_STOPPING", 0x9062);
        CONSTANT("BUS_METHOD_CALL_ABORTED", 0x9063);
        CONSTANT("BUS_CANNOT_ADD_INTERFACE", 0x9064);
        CONSTANT("BUS_CANNOT_ADD_HANDLER", 0x9065);
        CONSTANT("BUS_KEYSTORE_NOT_LOADED", 0x9066);
        CONSTANT("BUS_NO_SUCH_HANDLE", 0x906b);
        CONSTANT("BUS_HANDLES_NOT_ENABLED", 0x906c);
        CONSTANT("BUS_HANDLES_MISMATCH", 0x906d);
        CONSTANT("BT_MAX_CONNECTIONS_USED", 0x906e);
        CONSTANT("BUS_NO_SESSION", 0x906f);
        CONSTANT("BUS_ELEMENT_NOT_FOUND", 0x9070);
        CONSTANT("BUS_NOT_A_DICTIONARY", 0x9071);
        CONSTANT("BUS_WAIT_FAILED", 0x9072);
        CONSTANT("BUS_BAD_SESSION_OPTS", 0x9074);
        CONSTANT("BUS_CONNECTION_REJECTED", 0x9075);
        CONSTANT("DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER", 0x9076);
        CONSTANT("DBUS_REQUEST_NAME_REPLY_IN_QUEUE", 0x9077);
        CONSTANT("DBUS_REQUEST_NAME_REPLY_EXISTS", 0x9078);
        CONSTANT("DBUS_REQUEST_NAME_REPLY_ALREADY_OWNER", 0x9079);
        CONSTANT("DBUS_RELEASE_NAME_REPLY_RELEASED", 0x907a);
        CONSTANT("DBUS_RELEASE_NAME_REPLY_NON_EXISTENT", 0x907b);
        CONSTANT("DBUS_RELEASE_NAME_REPLY_NOT_OWNER", 0x907c);
        CONSTANT("DBUS_START_REPLY_ALREADY_RUNNING", 0x907e);
        CONSTANT("ALLJOYN_BINDSESSIONPORT_REPLY_ALREADY_EXISTS", 0x9080);
        CONSTANT("ALLJOYN_BINDSESSIONPORT_REPLY_FAILED", 0x9081);
        CONSTANT("ALLJOYN_JOINSESSION_REPLY_NO_SESSION", 0x9083);
        CONSTANT("ALLJOYN_JOINSESSION_REPLY_UNREACHABLE", 0x9084);
        CONSTANT("ALLJOYN_JOINSESSION_REPLY_CONNECT_FAILED", 0x9085);
        CONSTANT("ALLJOYN_JOINSESSION_REPLY_REJECTED", 0x9086);
        CONSTANT("ALLJOYN_JOINSESSION_REPLY_BAD_SESSION_OPTS", 0x9087);
        CONSTANT("ALLJOYN_JOINSESSION_REPLY_FAILED", 0x9088);
        CONSTANT("ALLJOYN_LEAVESESSION_REPLY_NO_SESSION", 0x908a);
        CONSTANT("ALLJOYN_LEAVESESSION_REPLY_FAILED", 0x908b);
        CONSTANT("ALLJOYN_ADVERTISENAME_REPLY_ALREADY_ADVERTISING", 0x908d);
        CONSTANT("ALLJOYN_ADVERTISENAME_REPLY_FAILED", 0x908e);
        CONSTANT("ALLJOYN_CANCELADVERTISENAME_REPLY_FAILED", 0x9090);
        CONSTANT("ALLJOYN_FINDADVERTISEDNAME_REPLY_ALREADY_DISCOVERING", 0x9092);
        CONSTANT("ALLJOYN_FINDADVERTISEDNAME_REPLY_FAILED", 0x9093);
        CONSTANT("ALLJOYN_CANCELFINDADVERTISEDNAME_REPLY_FAILED", 0x9095);
        CONSTANT("BUS_UNEXPECTED_DISPOSITION", 0x9096);
        CONSTANT("BUS_INTERFACE_ACTIVATED", 0x9097);
        CONSTANT("ALLJOYN_UNBINDSESSIONPORT_REPLY_BAD_PORT", 0x9098);
        CONSTANT("ALLJOYN_UNBINDSESSIONPORT_REPLY_FAILED", 0x9099);
        CONSTANT("ALLJOYN_BINDSESSIONPORT_REPLY_INVALID_OPTS", 0x909a);
        CONSTANT("ALLJOYN_JOINSESSION_REPLY_ALREADY_JOINED", 0x909b);
        CONSTANT("BUS_SELF_CONNECT", 0x909c);
        CONSTANT("BUS_SECURITY_NOT_ENABLED", 0x909d);
        CONSTANT("BUS_LISTENER_ALREADY_SET", 0x909e);
        CONSTANT("BUS_PEER_AUTH_VERSION_MISMATCH", 0x909f);
        CONSTANT("ALLJOYN_SETLINKTIMEOUT_REPLY_NOT_SUPPORTED", 0x90a0);
        CONSTANT("ALLJOYN_SETLINKTIMEOUT_REPLY_NO_DEST_SUPPORT", 0x90a1);
        CONSTANT("ALLJOYN_SETLINKTIMEOUT_REPLY_FAILED", 0x90a2);
        CONSTANT("ALLJOYN_ACCESS_PERMISSION_WARNING", 0x90a3);
        CONSTANT("ALLJOYN_ACCESS_PERMISSION_ERROR", 0x90a4);
        CONSTANT("BUS_DESTINATION_NOT_AUTHENTICATED", 0x90a5);
        CONSTANT("BUS_ENDPOINT_REDIRECTED", 0x90a6);
        CONSTANT("BUS_AUTHENTICATION_PENDING", 0x90a7);
        CONSTANT("BUS_NOT_AUTHORIZED", 0x90a8);
        CONSTANT("PACKET_BUS_NO_SUCH_CHANNEL", 0x90a9);
        CONSTANT("PACKET_BAD_FORMAT", 0x90aa);
        CONSTANT("PACKET_CONNECT_TIMEOUT", 0x90ab);
        CONSTANT("PACKET_CHANNEL_FAIL", 0x90ac);
        CONSTANT("PACKET_TOO_LARGE", 0x90ad);
        CONSTANT("PACKET_BAD_PARAMETER", 0x90ae);
        CONSTANT("PACKET_BAD_CRC", 0x90af);
        CONSTANT("STUN_ATTR_SIZE_MISMATCH", 0x90b0);
        CONSTANT("STUN_AUTH_CHALLENGE", 0x90b1);
        CONSTANT("STUN_SOCKET_NOT_OPEN", 0x90b2);
        CONSTANT("STUN_SOCKET_OPEN", 0x90b3);
        CONSTANT("STUN_FAILED_TO_SEND_MSG", 0x90b4);
        CONSTANT("STUN_FRAMING_ERROR", 0x90b5);
        CONSTANT("STUN_INVALID_ERROR_CODE", 0x90b6);
        CONSTANT("STUN_INVALID_FINGERPRINT", 0x90b7);
        CONSTANT("STUN_INVALID_ADDR_FAMILY", 0x90b8);
        CONSTANT("STUN_INVALID_MESSAGE_INTEGRITY", 0x90b9);
        CONSTANT("STUN_INVALID_MSG_TYPE", 0x90ba);
        CONSTANT("STUN_INVALID_ATTR_TYPE", 0x90bb);
        CONSTANT("STUN_RESPONSE_WITH_USERNAME", 0x90bc);
        CONSTANT("STUN_ERR400_BAD_REQUEST", 0x90bd);
        CONSTANT("STUN_BAD_INDICATION", 0x90be);
        CONSTANT("STUN_ERR401_UNAUTHORIZED_REQUEST", 0x90bf);
        CONSTANT("STUN_TOO_MANY_ATTRIBUTES", 0x90c0);
        CONSTANT("STUN_DUPLICATE_ATTRIBUTE", 0x90c1);
        CONSTANT("STUN_UNAUTHORIZED_INDICATION", 0x90c2);
        CONSTANT("ICE_ALLOCATING_MEMORY", 0x90c3);
        CONSTANT("ICE_CHECKS_INCOMPLETE", 0x90c4);
        CONSTANT("ICE_ALLOCATE_REJECTED_NO_RESOURCES", 0x90c5);
        CONSTANT("ICE_ALLOCATION_QUOTA_REACHED", 0x90c6);
        CONSTANT("ICE_ALLOCATION_MISMATCH", 0x90c7);
        CONSTANT("ICE_STUN_ERROR", 0x90c8);
        CONSTANT("ICE_INVALID_STATE", 0x90c9);
        CONSTANT("ICE_UNKNOWN_COMPONENT_ID", 0x90ca);
        CONSTANT("RENDEZVOUS_SERVER_DEACTIVATED_USER", 0x90cb);
        CONSTANT("RENDEZVOUS_SERVER_UNKNOWN_USER", 0x90cc);
        CONSTANT("UNABLE_TO_CONNECT_TO_RENDEZVOUS_SERVER", 0x90cd);
        CONSTANT("NOT_CONNECTED_TO_RENDEZVOUS_SERVER", 0x90ce);
        CONSTANT("UNABLE_TO_SEND_MESSAGE_TO_RENDEZVOUS_SERVER", 0x90cf);
        CONSTANT("INVALID_RENDEZVOUS_SERVER_INTERFACE_MESSAGE", 0x90d0);
        CONSTANT("INVALID_PERSISTENT_CONNECTION_MESSAGE_RESPONSE", 0x90d1);
        CONSTANT("INVALID_ON_DEMAND_CONNECTION_MESSAGE_RESPONSE", 0x90d2);
        CONSTANT("INVALID_HTTP_METHOD_USED_FOR_RENDEZVOUS_SERVER_INTERFACE_MESSAGE", 0x90d3);
        CONSTANT("RENDEZVOUS_SERVER_ERR500_INTERNAL_ERROR", 0x90d4);
        CONSTANT("RENDEZVOUS_SERVER_ERR503_STATUS_UNAVAILABLE", 0x90d5);
        CONSTANT("RENDEZVOUS_SERVER_ERR401_UNAUTHORIZED_REQUEST", 0x90d6);
        CONSTANT("RENDEZVOUS_SERVER_UNRECOVERABLE_ERROR", 0x90d7);
        CONSTANT("RENDEZVOUS_SERVER_ROOT_CERTIFICATE_UNINITIALIZED", 0x90d8);
        CONSTANT("BUS_NO_SUCH_ANNOTATION", 0x90d9);
        CONSTANT("BUS_ANNOTATION_ALREADY_EXISTS", 0x90da);
        CONSTANT("SOCK_CLOSING", 0x90db);
        CONSTANT("NO_SUCH_DEVICE", 0x90dc);
        CONSTANT("P2P", 0x90dd);
        CONSTANT("P2P_TIMEOUT", 0x90de);
        CONSTANT("P2P_NOT_CONNECTED", 0x90df);
        CONSTANT("BAD_TRANSPORT_MASK", 0x90e0);
        CONSTANT("PROXIMITY_CONNECTION_ESTABLISH_FAIL", 0x90e1);
        CONSTANT("PROXIMITY_NO_PEERS_FOUND", 0x90e2);
        CONSTANT("BUS_OBJECT_NOT_REGISTERED", 0x90e3);
        CONSTANT("P2P_DISABLED", 0x90e4);
        CONSTANT("P2P_BUSY", 0x90e5);
        CONSTANT("BUS_INCOMPATIBLE_DAEMON", 0x90e6);
        CONSTANT("P2P_NO_GO", 0x90e7);
        CONSTANT("P2P_NO_STA", 0x90e8);
        CONSTANT("P2P_FORBIDDEN", 0x90e9);
        CONSTANT("ALLJOYN_ONAPPSUSPEND_REPLY_FAILED", 0x90ea);
        CONSTANT("ALLJOYN_ONAPPSUSPEND_REPLY_UNSUPPORTED", 0x90eb);
        CONSTANT("ALLJOYN_ONAPPRESUME_REPLY_FAILED", 0x90ec);
        CONSTANT("ALLJOYN_ONAPPRESUME_REPLY_UNSUPPORTED", 0x90ed);
        CONSTANT("BUS_NO_SUCH_MESSAGE", 0x90ee);
        CONSTANT("ALLJOYN_REMOVESESSIONMEMBER_REPLY_NO_SESSION", 0x90ef);
        CONSTANT("ALLJOYN_REMOVESESSIONMEMBER_NOT_BINDER", 0x90f0);
        CONSTANT("ALLJOYN_REMOVESESSIONMEMBER_NOT_MULTIPOINT", 0x90f1);
        CONSTANT("ALLJOYN_REMOVESESSIONMEMBER_NOT_FOUND", 0x90f2);
        CONSTANT("ALLJOYN_REMOVESESSIONMEMBER_INCOMPATIBLE_REMOTE_DAEMON", 0x90f3);
        CONSTANT("ALLJOYN_REMOVESESSIONMEMBER_REPLY_FAILED", 0x90f4);
        CONSTANT("BUS_REMOVED_BY_BINDER", 0x90f5);

    }
    return constants;
}

_BusErrorInterface::_BusErrorInterface(Plugin& plugin)
    : ScriptableObject(plugin, Constants())
{
    QCC_DbgTrace(("%s", __FUNCTION__));

    ATTRIBUTE("name", &_BusErrorInterface::getName, 0);
    ATTRIBUTE("message", &_BusErrorInterface::getMessage, 0);
    ATTRIBUTE("code", &_BusErrorInterface::getCode, 0);
}

_BusErrorInterface::~_BusErrorInterface()
{
    QCC_DbgTrace(("%s", __FUNCTION__));
}

bool _BusErrorInterface::getName(NPVariant* result)
{
    ToDOMString(plugin, plugin->error.name, *result, TreatEmptyStringAsUndefined);
    return true;
}

bool _BusErrorInterface::getMessage(NPVariant* result)
{
    ToDOMString(plugin, plugin->error.message, *result, TreatEmptyStringAsUndefined);
    return true;
}

bool _BusErrorInterface::getCode(NPVariant* result)
{
    if (ER_NONE == plugin->error.code) {
        VOID_TO_NPVARIANT(*result);
    } else {
        ToUnsignedShort(plugin, plugin->error.code, *result);
    }
    return true;
}

