# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

Import('env')

libenv = env.Clone()


# Plugin library sources
srcs = libenv.Glob('*.cc')
if '' != libenv.subst('$GECKO_BASE'):
    libenv.Append(CPPPATH = [libenv.Dir('.').srcnode(), libenv.Dir('npapi').srcnode(), libenv.subst('$GECKO_BASE/include')])
    srcs.append(libenv.Glob('npapi/*.cc'))
else:
    libenv.Append(CPPPATH = [libenv.Dir('.').srcnode(), libenv.Dir('cordova').srcnode()])
    srcs.append(libenv.Glob('cordova/*.cc'))
    srcs.append(libenv.Glob('cordova/${OS_CONF}/*.cc'))
srcs.append(libenv.Glob('os/${OS_CONF}/*.cc'))

objs = libenv.SharedObject(srcs)
if libenv['OS_CONF'] == 'windows':
    objs.append(['os/${OS_CONF}/npalljoyn.def', libenv.RES('os/${OS_CONF}/npalljoyn.rc')])

if libenv['LIBTYPE'] == 'both':
    # Need to replace the shared alljoyn library with the static one for linking the plugin.
    libs = libenv['LIBS']
    libs[libs.index('alljoyn')] = libenv.File('$DISTDIR/cpp/lib/${LIBPREFIX}alljoyn${LIBSUFFIX}')
    libenv.Replace(LIBS = libs)

# Plugin library
npalljoyn = libenv.SharedLibrary('npalljoyn', objs)
shlibs = ['npalljoyn']

Return(shlibs)