# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

Import('env')

samples_env = env.Clone()

if samples_env['BR'] == 'on':
    # Build apps with bundled daemon support
    samples_env.Prepend(LIBS = [samples_env['ajrlib']])

samples_env.Prepend(LIBS = samples_env['ALLJOYN_C_LIB_STATIC'])

# Basic Sample programs
samples_env.SConscript('basic/SConscript', exports = {'env': samples_env })

# About Sample programs
samples_env.SConscript('about/SConscript', exports = {'env': samples_env })

# Security Sample programs
samples_env.SConscript('secure/SConscript', exports = {'env': samples_env })

# Observer Sample programs
samples_env.SConscript('observer/SConscript', exports = {'env': samples_env })