# Copyright (c) 2010 - 2011, 2013 - 2014 AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 

Import('env')

samples_env = env.Clone()

samples_env.Prepend(LIBS = samples_env['ALLJOYN_C_LIB_STATIC'])

if samples_env['BR'] == 'on':
    # Build apps with bundled daemon support
    samples_env.Prepend(LIBS = [samples_env['brobj'], samples_env['ajrlib']])

# Basic Sample programs
samples_env.SConscript('basic/SConscript', exports = {'env': samples_env })

# Security Sample programs
samples_env.SConscript('secure/SConscript', exports = {'env': samples_env })
