# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 

Import('router_env', 'router_objs', 'srobj')

# Build the resources for the dll
rsc = router_env.RES('DaemonResources.rc')

daemon_static_lib = [];
daemon_shared_lib = [];

# Build the Windows daemon.
router_libs = router_env.SharedLibrary('daemonlib', ['daemon-service.cc', 'daemon-main.cc'] + srobj + router_objs + rsc)

# the variable router_libs contains the file nodes for the  static library and the 
# shared library however it may contain more files such as .pdb files on windows.  
# Search through the list and assign the static library to daemon_static_lib  and 
# the shared library to daemon_shared_lib variable.
for x in router_libs: 
    if router_env['LIBSUFFIX'] in str(x):
        daemon_static_lib = x;
    if router_env['SHLIBSUFFIX'] in str(x):
        daemon_shared_lib = x;

router_env.Install('$CPP_DISTDIR/lib', daemon_static_lib) #put the *.lib file in the lib folder
env2 = router_env.Clone();
env2.Append(LIBS = ['daemonlib'])
daemon = []

progs = [daemon, daemon_shared_lib] # daemonlibs.dll will be returned
Return('progs')