# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#

Import('router_env', 'router_objs', 'srobj')
from os.path import basename

# Test Programs
if router_env['OS'] == 'iOS':
    progs = []
else:
    progs = [
        router_env.Program('advtunnel', ['advtunnel.cc'] + srobj + router_objs),
        router_env.Program('ns', ['ns.cc'] + srobj + router_objs)
    ]

    if router_env['OS'] in ['android', 'linux', 'win7', 'win10']:
        progs.append(router_env.Program('bbdaemon', ['bbdaemon.cc'] + srobj + router_objs))
        progs.append(router_env.Program('ardp',     ['ardp.cc'] +     srobj + router_objs))
        progs.append(router_env.Program('ardptest', ['ardptest.cc'] + srobj + router_objs))

Return('progs')