# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 
Import('env')
clientDistDir = '$CPP_DISTDIR/samples/observer'

# Sample Programs
progs = [
    env.Program('door_provider',  ['door_provider.cc']),
    env.Program('door_consumer',  ['door_consumer.cc']),
    ]

if env['OS'] in ['linux', 'darwin']:
    env.Install('$CPP_DISTDIR/bin/samples', progs )
    env.Install(clientDistDir, env.Glob('*.cc'))
    env.Install(clientDistDir, 'Makefile')
    env.Install(clientDistDir, 'README.txt')
