# Copyright (c) 2016 Open Connectivity Foundation (OCF) and AllJoyn Open
#    Source Project (AJOSP) Contributors and others.
#
#    SPDX-License-Identifier: Apache-2.0
#
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Copyright 2016 Open Connectivity Foundation and Contributors to
#    AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for
#    any purpose with or without fee is hereby granted, provided that the
#    above copyright notice and this permission notice appear in all
#    copies.
#
#     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
#     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
#     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
#     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
#     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
#     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
#     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
#     PERFORMANCE OF THIS SOFTWARE.
# 

Import('env')

vars = Variables()
vars.Add(BoolVariable('TSAN', 'Enable Thread Sanitizer runtime checks', 'no'))
vars.Add(BoolVariable('IGNORE_STRICT', 'Ignore strict compiler warnings', 'no'))
vars.Update(env)

# Linux specific flags

# Force 64-bit builds
env.Append(CXXFLAGS=['-m64', '-fPIC'])
env.Append(CFLAGS=['-m64', '-fPIC'])
env.Append(LINKFLAGS=['-m64'])

# Thread sanitizer control
if env['TSAN']:
   env.Append(CFLAGS = ['-fno-omit-frame-pointer', '-fasynchronous-unwind-tables', '-funwind-tables', '-fsanitize=thread', '-fPIE'])
   env.Append(CXXFLAGS = ['-fno-omit-frame-pointer', '-fasynchronous-unwind-tables', '-funwind-tables', '-fsanitize=thread', '-fPIE'])
   env.Append(LINKFLAGS = ['-fsanitize=thread', '-pie'])
#   if env['CXX'] != 'clang':
#      env.AppendUnique(LIBS = ['tsan'])

if env['IGNORE_STRICT']:
   env.Append(CXXFLAGS=['-Wno-error'])
   env.Append(CFLAGS=['-Wno-error'])
