# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#

Import('env')

# The return value is the collection of files installed in the build destination.
returnValue = env.SConscript('JavaSDKDocAboutClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocAboutService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocAutoPingerSample/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecureDoorService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecureDoorClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocMethodsClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocMethodsService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocPropertiesClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocPropertiesService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecurityLogonClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecurityLogonService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecuritySRPClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSecuritySRPService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSignalClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocSignalService/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocIntrospectWithDescriptionClient/SConscript', exports = ['env'])
returnValue += env.SConscript('JavaSDKDocIntrospectWithDescriptionService/SConscript', exports = ['env'])

Return('returnValue')