# Copyright (c) 2010 - 2011, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 

import os
Import ('locenv', 'common_objs')

if locenv['OS'] == 'win8':
    locenv.Append(CXXFLAGS=['\"/FU%s\"' % '$ALLJOYN_DIST\\bin\\AllJoyn.winmd'])
    locenv.Append(CPPDEFINES=['_WINRT_DLL'])
    winmdswitch = '\"/WINMDFILE:%s\"' % os.path.abspath('AllJoynStreaming.winmd')
    locenv.Append(LINKFLAGS=['/MANIFEST:NO', '/SUBSYSTEM:CONSOLE', '/TLBID:1', '/APPCONTAINER', '/WINMD', winmdswitch])

    srcs = [ f for f in locenv.Glob('*.cc')]
    src_objs = locenv.Object(srcs)
    locenv.Depends(src_objs, '$ALLJOYN_DIST\\bin\\AllJoyn.winmd')
    dll = [
        locenv.SharedLibrary('AllJoynStreaming', src_objs + common_objs),
        ]
    locenv.Install('$DISTDIR/bin', dll)

Return('dll')