# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('sample_env')

jars = []
# The config client sample is an Android project and is not currently set up to
# build using SCons. Prevent Build Failure if None is returned.
configClient_jars = sample_env.SConscript('ConfigClientSample/SConscript', exports = ['sample_env'])
if configClient_jars != None:
    jars += configClient_jars
Return('jars')