/*------------------------------------------------------------------------------
* This is an autogenerated or copied file which AllSeen Alliance,
* as author hereby dedicates to the public domain.  Additionally, THIS
* SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND ANY CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE,
* AND OF GOOD TITLE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
* CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
* OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
* ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*------------------------------------------------------------------------------*/
////////////////////////////////////////////////////////////////////////////////
//
//  ALLJOYN MODELING TOOL - GENERATED CODE
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//
//  ObserverTestObjects.m
//
////////////////////////////////////////////////////////////////////////////////

#import "ObserverTestObjects.h"

////////////////////////////////////////////////////////////////////////////////
//
//  Objective-C Bus Object implementation for TestJustA
//
////////////////////////////////////////////////////////////////////////////////

@implementation TestJustA

- (void)identifyAWithBusname:(NSString**)busname andPath:(NSString**)path message:(AJNMessage *)methodCallMessage
{
    // get hidden property via KVO observing
    *busname = [NSString stringWithString:((AJNBusAttachment *)[self valueForKey:@"bus"]).uniqueName];
    *path = [NSString stringWithString:self.path];

}


@end

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//
//  Objective-C Bus Object implementation for TestJustB
//
////////////////////////////////////////////////////////////////////////////////

@implementation TestJustB

- (void)identifyBWithBusname:(NSString**)busname andPath:(NSString**)path message:(AJNMessage *)methodCallMessage
{
    // get hidden property via KVO observing
    *busname = [NSString stringWithString:((AJNBusAttachment *)[self valueForKey:@"bus"]).uniqueName];
    *path = [NSString stringWithString:self.path];
}


@end

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//
//  Objective-C Bus Object implementation for TestBoth
//
////////////////////////////////////////////////////////////////////////////////

@implementation TestBoth

- (void)identifyAWithBusname:(NSString**)busname andPath:(NSString**)path message:(AJNMessage *)methodCallMessage
{
    // get hidden property via KVO observing
    *busname = [NSString stringWithString:((AJNBusAttachment *)[self valueForKey:@"bus"]).uniqueName];
    *path = [NSString stringWithString:self.path];
}

- (void)identifyBWithBusname:(NSString**)busname andPath:(NSString**)path message:(AJNMessage *)methodCallMessage
{
    // get hidden property via KVO observing
    *busname = [NSString stringWithString:((AJNBusAttachment *)[self valueForKey:@"bus"]).uniqueName];
    *path = [NSString stringWithString:self.path];
}


@end

////////////////////////////////////////////////////////////////////////////////
