# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

# 
Import('env')
clientDistDir = '$CPP_DISTDIR/samples/basic'

# Sample Programs
progs = [
    env.Program('basic_service',  ['basic_service.cc']),
    env.Program('basic_client',   ['basic_client.cc']),
    env.Program('signal_service', ['signal_service.cc']),
    env.Program('nameChange_client', ['nameChange_client.cc']),
    env.Program('signalConsumer_client', ['signalConsumer_client.cc']),
    ]

if env['OS'] in ['linux', 'darwin']:
    env.Install('$CPP_DISTDIR/bin/samples', progs )
    env.Install(clientDistDir, env.Glob('*.cc'))
    env.Install(clientDistDir, 'Makefile')
    env.Install(clientDistDir, 'README.txt')

elif env['OS_GROUP'] == 'windows':
    env.Install('$CPP_DISTDIR/bin/samples', progs )
    env.Install(clientDistDir, env.Glob('*.cc'))
    env.InstallAs(clientDistDir + '/README.txt', 'README.windows.txt')
    #install Visual Studio solution files
    env.Install(clientDistDir+'/VC2008Win7', 'VC2008Win7/VC2008Win7.sln')
    env.Install(clientDistDir+'/VC2008Win7/basic_client', 'VC2008Win7/basic_client/basic_client.vcproj')
    env.Install(clientDistDir+'/VC2008Win7/basic_service', 'VC2008Win7/basic_service/basic_service.vcproj')
    env.Install(clientDistDir+'/VC2008Win7/nameChange_client', 'VC2008Win7/nameChange_client/nameChange_client.vcproj')
    env.Install(clientDistDir+'/VC2008Win7/signal_service', 'VC2008Win7/signal_service/signal_service.vcproj')
    env.Install(clientDistDir+'/VC2008Win7/signalConsumer_client', 'VC2008Win7/signalConsumer_client/signalConsumer_client.vcproj')